### ISSUE TITLE
enhance telemetry

### ISSUE THREAD

**Issue by mstrYoda** [authzed/spicedb#1007]
Hi all, I think it would be nice to have enhanced telemetry in spicedb prometheus metrics like execution time. WDYT about it?

**Comment by mstrYoda** [comment]
Hi @vroldanbet, I mean the execution time for operations like CheckPermissionRequest would be nice to see in exposed metrics.

**Comment by vroldanbet** [comment]
@mstrYoda we use https://github.com/grpc-ecosystem/go-grpc-prometheus to get prometheus latency histograms out of RPC calls, so it should work out of the box. Did you experience this wasn't the case?

**Comment by mstrYoda** [comment]
> @mstrYoda we use https://github.com/grpc-ecosystem/go-grpc-prometheus to get prometheus latency histograms out of RPC calls, so it should work out of the box. Did you experience this wasn't the case?

Well I think this points out the request for the clients, right? But what I actually wanted to see is the internal computation time inside the SpiceDB.

**Comment by vroldanbet** [comment]
I'm not sure I follow - `go-grpc-prometheus` is added as a middleware to the gRPC API, so for any inbound gRPC call SpiceDB will emit metrics.

**Comment by josephschorr** [comment]
@mstrYoda Any additional help you need with configuring this?

**Comment by josephschorr** [comment]
Closing. Please reopen if you have any further ideas or questions
