### ISSUE TITLE
Add support for nested arrows

### ISSUE THREAD

**Issue by josephschorr** [authzed/spicedb#1022]
Now that V0 API is fully removed, we should investigate adding support for nested arrows

Example:

```zed
definition namespace {
  relation view: user
}

definition namespace {
  relation parent: organization
}

definition document {
  relation parent: namespace
  permission view = parent->parent->view
}
```

**Comment by jzelinskie** [comment]
This is a duplicate of: https://github.com/authzed/spicedb/issues/15

**Comment by artie-shevchenko** [comment]
can we change the priority of this ticket to get rid of the synthetic permission in user-defined roles: [Modeling Google Cloud IAM in SpiceDB](https://authzed.com/blog/google-cloud-iam-modeling#user-content-using-roles-to-make-decisions)?
