### ISSUE TITLE
could not CREATE relationship when using TOUCH

### ISSUE THREAD

**Issue by williamdclt** [authzed/spicedb#1038]
Version: 1.13.0 and 1.14.1 

From time to time, I'm getting this error: `could not CREATE relationship XXX#YYY@ZZZ:*, as it already existed. If this is persistent, please switch to TOUCH operations or specify a precondition`.

I do use TOUCH, and never ever CREATE. It looks like a bug in SpiceDB? possibly a race condition (it doesn't happen often, about once a day), if SpiceDB does a `DELETE` and `CREATE` under the hood to simulate a `TOUCH`

**Comment by josephschorr** [comment]
#901 is now merged. @williamdclt please reopen if you encounter after testing with it
