### ISSUE TITLE
spicedb docker container is not persistent after stop

### ISSUE THREAD

**Issue by danmunteanuevo** [authzed/spicedb#1072]
I use windows docker.
And if I stop the docker container from Windows Docker or by closing the CMD in which I started the container, it gets removed from the list of containers instead of just switching to stopped.
Thus I cannot start it again from windows docker, I can only each time start a new one and keep CMD open if I want to use the docker. Probably some issue with the docker image for windows docker.

**Comment by danmunteanuevo** [comment]
This actual a documentation issue due to the --rm param indicated in the https://authzed.com/docs/spicedb/installing
Which should not be there.

**Comment by dsieczko** [comment]
Thanks @danmunteanuevo ! We'll take a look at updating the docs.
