### ISSUE TITLE
Missing index for GC

### ISSUE THREAD

**Issue by williamdclt** [authzed/spicedb#1090]
I've noticed that there's a missing index for the Postgres GC since 1.14 (maybe MySQL too?).

Until 1.13.0 there was an index on `deleted_transaction` which was used. The migration to 1.14.1 replaces `deleted_transaction` with `deleted_xid`, which drops the index silently. 1.14.1 does not include an index on `deleted_xid` to replace the old one.

This means that the GC consumes a huge amount of CPU and IOPS. This can lead to performance problems, or to high bills at the end of the month if using something like AWS RDS Aurora which bills by IOPS.

I've worked around it by creating my own index, but it probably should be added to SpiceDB:

```sql
CREATE INDEX CONCURRENTLY custom_ix_relation_tuple_by_deleted_xid ON public.relation_tuple USING btree (deleted_xid);
```

**Comment by williamdclt** [comment]
I'm not sure that's the same thing. In the GC case, the index wasn't covering either in 1.13 (which wasn't a problem): the problem is that the `WHERE` filter `deleted_xid < $1` isn't indexed at all which means it does a seq scan.

Adding an index on `deleted_xid` seems to solve the problem for me, even without a covering index.

**Comment by josephschorr** [comment]
@williamdclt correct, but the referenced change is ensuring that we have index coverage for GC entirely, amongst other queries
