### ISSUE TITLE
spicedb migrate does not output help text

### ISSUE THREAD

**Issue by easyCZ** [authzed/spicedb#1100]
When `spicedb migrate` is invoked, no help text is provided.

This becomes even more confusing when I forget to specify the `revision` in the command. This outputs no information, and exists with status code 1.
```
spicedb migrate \
    --datastore-conn-uri='<URI>' \
    --datastore-engine="mysql" \
    --log-level="debug"
```

The fix here would be to validate the input arguments and fail with the help text, if the `revision` is not provided/valid.

**Comment by vroldanbet** [comment]
Thanks for the report! I've opened https://github.com/authzed/spicedb/pull/1101 to address it
