### ISSUE TITLE
Question: Renaming definitions and relations

### ISSUE THREAD

**Issue by alex-pobeditel-2004** [authzed/spicedb#1122]
Hi! Is there a way to rename some definitions/relations in spicedb schema?

During development schema expanded several times and now some names became ambiguous. Looks like it will be better to at least add different prefixes for some definitions and relations.  
I didn't find any official way to migrate names, but maybe there are any hacks to do so? Like search/replace substrings in database (with understanding how dangerous it can be). Any ideas?

**Comment by vroldanbet** [comment]
@alex-pobeditel-2004 unfortunately we cannot recommend directly manipulating the database. Just like relational database, renaming definitions is a breaking change. SpiceDB is designed to prevent that kind of disruptive operations by rejecting changes to the schema that remove relations with actual data.

Our recommendation is to do a multi-step migration:

- add new definitions and relations to the schema, keep old ones
- start writing relationships to new relations along old relations (a.k.a "dual-write")
- run backfill job (copy data from old relations to new relations)
- update permissions to start using new data or even create new permissions (the latter allows you to switch back your client app in case something is not working as intended)
- stop writing to old relations
- delete old relationships
- remove old relations and objects from schema

Hope that helps!

**Comment by alex-pobeditel-2004** [comment]
@vroldanbet nice idea, thanks! I think this is quite a clear and rational way to do solve the problem :)  
So I think this issue can be closed 🙏
