### ISSUE TITLE
Some mySQL URIs unable to be parsed by url.Parse

### ISSUE THREAD

**Issue by captiosus** [authzed/spicedb#1157]
The changes introduced by https://github.com/authzed/spicedb/pull/1129 cause mySQL URIs generated with https://pkg.go.dev/github.com/go-sql-driver/mysql#Config.FormatDSN to not work. The DSNs generated by the library are not able to be parsed by `url.Parse`. Can this be updated to use https://pkg.go.dev/github.com/go-sql-driver/mysql#ParseDSN instead of `url.Parse` or is the intention that SpiceDB only accepts URI connection strings?

**Comment by josephschorr** [comment]
Will change to use the ParseDSN method tomorrow
