### ISSUE TITLE
CockroachDB GC Window Change

### ISSUE THREAD

**Issue by chancesm** [authzed/spicedb#1158]
The default datastore gc window in SpiceDB is 24 hours. This worked well as Cockroach's default gc window was 25 hours. When the datastore gc window is less than what spicedb is configured to use, an error occurs. CockroachDB is planning on dropping the default GC window down to 4 hours for their dedicated clusters (1.25 hours for serverless). This change will cause Spicedb to error out as the default values will end up conflicting. The change is documented here: https://github.com/cockroachdb/cockroach/issues/89233

Suggested solution: Change Spicedb's default datastore gc window to a value that matches one of CockroachDB's new default values (4 hours or 1.25 hours) so that new adopters do not run into issues when exploring Spicedb for the first time.

**Comment by vroldanbet** [comment]
Unfortunately, we cannot change the default GC value as it would be a breaking change to SpiceDB deployments where client applications rely on `at_exact_snapshot` or `Watch` API. We added a new section in our documentation and referenced it in the logged error message.
