### ISSUE TITLE
Schema write bugs: updates causes 5-10 sec /permissions/check to answer falsely

### ISSUE THREAD

**Issue by muntdan** [authzed/spicedb#1201]
I am using latest docker available 1.17 with PostgresDB 15 and have the fallowing issue:

FIY: also on any Schema writes no matter if it is new or identically SAME schema makes the api method /permissions/check to return false response for approximately 5-10sec (like the user has no access) and I am using MinimizeLatency = true.

**Comment by ayrbox** [comment]
From my understanding, `minimizelatency` is not reliable as it uses any cache.  Use of `fullConsistency` helps there will be performance hit for large set of data. Best option would be use `at_least_as_fresh` but you would required store zed token some where.

You can read more here https://authzed.com/docs/reference/api-consistency

**Comment by josephschorr** [comment]
@muntdan I was unable to reproduce this issue with Postgres 15 and HEAD of SpiceDB. Can you give detailed repro instructions, including schema, sample relationships and the exact API call you're making?

**Comment by muntdan** [comment]
This is the full schema: https://play.authzed.com/s/eHL01d2652g2/schema
I did a small fix for the team has_write (added the has_delete also in front as it was forgotten/missed) :
permission has_write = **has_delete** + write_user + parent_customer->has_write + parent_team->has_write
I used the REST schema/write to update the new schema
For the next 5-10 seconds the  /permissions/check for an existing write_user started replying PERMISSIONSHIP_NO_PERMISSION although he was not even among the has_delete users.
I retested with another schema/write with exact same json ..so no changes 
Same behavior 5-10 seconds the  /permissions/check for that user write_user says PERMISSIONSHIP_NO_PERMISSION

**Comment by josephschorr** [comment]
@muntdan can you see if you can reproduce the problem using `zed` to write the schema and do the checks? I've been unable to reproduce the issue locally against Postgres using `zed`

**Comment by muntdan** [comment]
I dont have zed available for windows/docker.
I am inclined this is related to Postgres like  https://github.com/authzed/spicedb/issues/1215 according to @vroldanbet
so maybe will also get fixed in the upcoming 1.18

**Comment by josephschorr** [comment]
@muntdan if it were related, I'd have expected it to be reproducible locally; you're saying it occurs every time you try? `zed` can be installed via docker

**Comment by muntdan** [comment]
This was fixed by latest 1.18 release
