### ISSUE TITLE
Proposal: Extend object IDs to support more values and encodings

### ISSUE THREAD

**Issue by jakedt** [authzed/spicedb#1210]
# Situation

Right now the regex for object IDs is: `^(([a-zA-Z0-9_][a-zA-Z0-9/_|-]{0,127})|\\*)$`

Visualized by: https://regexper.com/#%5E%28%28%5Ba-zA-Z0-9_%5D%5Ba-zA-Z0-9%2F_%7C-%5D%7B0%2C127%7D%29%7C%5C*%29%24

Currently addressed use cases for this regex are:
- conforming hand-crafted object IDs
- Many Auth0 subject IDs which contain the provider name, a liter `|` and then the provider's unique identifier
- Base64 identifiers in url-safe encoding

Standard types that are known to not work natively:
- emails (contain `@` and `.`)
- JWT [sub claims](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.2) that contain URIs (contain `:`, `/`, `.`, `%` and others) or are otherwise non-conformant
- values which are longer than 128 characters in a conforming encoding.
- Standard Base64 values (contain `=`, `+`, and `/`)

The current guidance for using non-confirming types is to [base64 encode](https://en.wikipedia.org/wiki/Base64) them or one-way hash them.

One-way hashing is irreversible, which makes `LookupSubject` and `LookupResources` results less useful.

Base64 encoding increases the byte-length of the data by 1/3 due to storing 24 bits of binary data in 32 bits of ascii characters.
This is problematic because certain types are already quite long _before_ encoding. For example, an email can be up to 320 characters long before encoding, resulting in a string up to 427 characters after encoding.

It is non-trivial to arbitrarily extend the character set allowed. Right now object IDs are sometimes encoded directly into strings (for example, AuthZed's playground and zed validate file format), and some of the extended characters would make parsing these strings ambiguous.

It is also non-trivial to extend the length of the field, because the current object_id length assumptions may be baked into [spicedb](https://github.com/authzed/spicedb) datastore drivers or client storage. The latter is mitigated by the fact that the client would have had to give the value to the API in order to receive it back.

# Target

Ideally we would support more types, either natively or through encoding. In all cases, the length of the current object ID should be extended. For storage in the zed and playground file format, IDs could be encoded before serialization, allowing the use of extended characters in the API. For a partially extended character set, we might be able to keep the parser predictive (i.e. no backtracking) without encoding.

# Proposal (subject to discussion)

- Audit existing SpiceDB datastore implementations to verify compatibility with longer object IDs
- Poll the community (through this issue and other means) about whether extending the field length would cause them trouble
- Extend the `object_id` field to 1024 ascii characters.
- Extend the allowed encoding to accept `=`, `/`, and `+` to allow for standard Base64 values

**Comment by MarceloPeresToi** [comment]
+1

**Comment by akram-hameed** [comment]
+1 from me, too.

**Comment by mcc513** [comment]
+1 especially for extending the length. To get quick win/traction, is it worth considering splitting this into two separate issues?
