### ISSUE TITLE
Bulk Permission Checking

### ISSUE THREAD

**Issue by ayrbox** [authzed/spicedb#1214]
Hello everyone, 

My team is using Spicedb as one source of truth  to store relationships. That saying we have relation in the database. 
Everything is stored in spicedb and we are using `LookupResource` and `LookupSubject` to read relations.

Lets say I have schema as follows, and I need to list all the document `userA` has **write** but within a `folderA`. Assuming that there is 000s of folder and 000s documents, is there a way to do lookups efficiently?

At the moment, what I am doing is fetching all the documents within a folder. Then checking `write` permission for each document for given user. 

```
definition user {}

definition folder {
	relation parent: folder;
	relation owner: user;
	
	permission can_manage = owner;
	permission can_read = owner;
}

definition document {
  relation folder: folder
  relation direct_user: user

  permission can_read = direct_user + folder->can_read
  permission can_write = direct_user + folder->can_manage
}
```

Thank you in advance 🙏

**Comment by josephschorr** [comment]
You'd use the LookupResources API: https://buf.build/authzed/api/docs/main:authzed.api.v1#authzed.api.v1.PermissionsService.LookupResources

However, after a certain point it will become slower, so there is this current proposal: https://github.com/authzed/spicedb/issues/207

**Comment by ayrbox** [comment]
Thank for the response @josephschorr
