### ISSUE TITLE
support pgbouncer with SpiceDB Postgres datastore w/o session pooler mode

### ISSUE THREAD

**Issue by vroldanbet** [authzed/spicedb#1217]
a few users have reported that having pgbouncer in front of Postgres does not work with the PG datastore. See this [discord discussion](https://discord.com/channels/844600078504951838/844600078948630559/1060960536117907517):

````
2 UNKNOWN: unable to find revision: ERROR: prepared statement \"lrupsc_89_0\" does not exist (SQLSTATE 26000)
````

[Another user reported](https://github.com/authzed/spicedb/issues/1992) an error like:
```
prepared statement name is already in use (SQLSTATE 08P01)
```

The issue seems to originate from the fact that SpiceDB uses a pgx execution mode that does 2 roundtrips, one to prepare the statement and another to execute it. PGBouncer would presumably switch the underlying connections, which can lead to errors like the above described. 

The current workaround, as described by some SpiceDB users, is to configure PgBouncer with connection pooler mode set to `session` and to ignore `plan_cache_mode` with `ignore_startup_parameters=plan_cache_mode`.

Ideally, a sustainable long-term solution is found that does not involve configuring specific settings in PgBouncer.

**Comment by vroldanbet** [comment]
Reopening as we are now testing it, but not documenting it, @bradengroom would you be so kind to add some docs? 🙏🏻 I think https://github.com/authzed/docs/blob/main/docs/spicedb/selecting-a-datastore.md would be the right place

**Comment by sashayakovtseva** [comment]
As I understand, session_pooling is the only possible way to use pgbouncer and it's not planned to support tx_pooling, correct?

**Comment by vroldanbet** [comment]
@sashayakovtseva from the work done by @bradengroom in https://github.com/authzed/spicedb/pull/1626, and also from a cursory look online, it appears that SpiceDB would need `session_pooling` for prepared statements. SpiceDB now has a nice test-suite contributed by @bradengroom that could help determining if it works.

It does not mean that _it won't be supported_, if there is a critical mass of folks requesting this, it could be supported, at the expense of query performance degradation (as you can see from https://github.com/authzed/spicedb/pull/1626).

I think some of the work on https://github.com/authzed/spicedb/pull/1626 could be reused to support having folks disabling prepared statements.

**Comment by pdeaudney** [comment]
In PostgreSQL you can also set GUC values such as `plan_cache_mode` on the database or user. https://www.postgresql.org/docs/current/config-setting.html#CONFIG-SETTING-SQL

```
spicedb=> alter user spicedb SET plan_cache_mode = force_custom_plan;
ALTER ROLE
```
or
```
spicedb=> alter DATABASE spicedb SET plan_cache_mode = force_custom_plan;
ALTER DATABASE
```
You can also set these at user/db creation time too I believe.

After altering the user or db, if you reconnect the `plan_cache_mode` will be set.
```
spicedb=> show plan_cache_mode;
  plan_cache_mode
-------------------
 force_custom_plan
```
If it is not set, the value you would see will be `auto`.

I haven't tested this yet with pgbouncer operating in session pooling mode, with prepared transaction support enabled and ignoring the startup parameter beyond confirming spicedb will startup.

But this combination might resolve the performance regressions observed in #1626 when using pgbouncer without prepared transactions.
