### ISSUE TITLE
Unsupported expression error when reading/writing schema with caveats

### ISSUE THREAD

**Issue by rikkuness** [authzed/spicedb#1261]
When loading a schema that contains a caveat with an expression, I'm unable to read/write a schema using `zed`. The schema behaves as expected in the playground, except for if you open the **zed terminal** and invoke `zed schema read` I get the error
```
invalid caveat expression: unsupported expression: id:13 comprehension_expr:{iter_var:"i" iter_range:{id:1 ident_expr:{name:"somelist"}} accu_var:"__result__" accu_init:{id:7 const_expr:{bool_value:true}} loop_condition:{id:9 call_expr:{function:"@not_strictly_false" args:{id:8 ident_expr:{name:"__result__"}}}} loop_step:{id:11 call_expr:{function:"_&&_" args:{id:10 ident_expr:{name:"__result__"}} args:{id:5 call_expr:{function:"_>=_" args:{id:4 ident_expr:{name:"i"}} args:{id:6 const_expr:{int64_value:42}}}}}} result:{id:12 ident_expr:{name:"__result__"}}}
```

Interestingly if I change the expression to `42 in somelist` rather than using `.all()` then I can read the schema back out, so it looks to be something to do with the macros? The code included at https://github.com/authzed/spicedb/blob/main/pkg/caveats/env.go#L75-L78 is perhaps missing somewhere either in `zed`? I've not tried to write the schema directly via the API yet to confirm if it is a zed issue.

Playground link:
https://play.authzed.com/s/DFdJCbMCry9n/schema

**Comment by rikkuness** [comment]
I think the `zed schema read` in the playground may be slightly misleading as _any_ zed command in the playground throws the same error so it could be just that the playground tries to write the schema before any zed command?

When this actually seems to occur is computing a diff between existing and updated schemas. I created a totally new local SpiceDB and was able to write a schema with caveats, if I then try to write any more caveats and update the schema, that's when I get the expression error.

**Comment by josephschorr** [comment]
> if I then try to write any more caveats and update the schema, that's when I get the expression error.

You get this error from `zed` or from the Playground or the API or...?

**Comment by rikkuness** [comment]
So it appears to be coming from `zed` both using `zed` from the playground and locally. Although it just seems to be that it's a dependency update issue, `zed` is using `github.com/authzed/spicedb v1.15.1` which is missing the caveat compilation stuff. Pulling the `zed` codebase locally and updating the spicddb dep to `v1.19.0` seems to resolve the issue.

Pull request incoming on the zed repo :)

**Comment by rikkuness** [comment]
Excellent. Thanks for the quick merge!

**Comment by vroldanbet** [comment]
📢 zed `v0.10.1` has been released https://github.com/authzed/zed/releases/tag/v0.10.1
