### ISSUE TITLE
Apparently spurious Postgres unserializable transaction errors reported in SpiceDB log

### ISSUE THREAD

**Issue by benanhalt** [authzed/spicedb#1269]
We're seeing occasional error level log messages from SpiceDB like the following when writing relationships:
```
{"level":"error","module":"pgx","args":["task","c18caf9f-2a32-4908-a215-b701edc17104","mission","mission","f0366269-65fb-485d-826d-fe84d98efb78","...","",null],"err":"ERROR: could not serialize access due to read/write dependencies among transactions (SQLSTATE 40001)","pid":21837,"sql":"INSERT INTO relation_tuple (namespace,object_id,relation,userset_namespace,userset_object_id,userset_relation,caveat_name,caveat_context) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)","time":0.444901,"time":"2023-04-04T19:35:07Z","message":"Exec"}
```
I'm able to reliably reproduce these errors using the `zed import` tool by running two instances concurrently importing a large number of relationships.

The errors appear to be spurious as the relationships end up getting written. It seems, based on the implementation in https://github.com/authzed/spicedb/blob/2490969c415736081a2f3941591d10328b61f3fb/internal/datastore/postgres/postgres.go#L319 that these are expected, retry-able errors arising in the pgx module. If that is the case, it would be better if they weren't reported as error level log messages in the SpiceDB logs as it complicates alerting on legitimate errors.

**Comment by josephschorr** [comment]
This error is being raised by the underlying SQL library `pgx`; I suspect the best approach (for now) would be to ignore any errors from it and only consume those being returned by SpiceDB.

The only workaround I see would be to register a custom logger with `pgx` and eat these errors, but that has issues around other log lines that may make it undesirable
