### ISSUE TITLE
Endless loop in watch stream

### ISSUE THREAD

**Issue by aberkovsky** [authzed/spicedb#1272]
We have the following problem, if we concurrently add two packs of relationships (in this case 2 batches of 5 relationships), then the watch service enters an endless loop, constantly giving back the latest records.
Originally was reproduced on version 1.19.1 but then clarified, reproduced on version 1.17.0, everything worked correctly on version 1.16.2

As I understand it, the problem is how the next snapshot is determined ([watch.js](https://github.com/authzed/spicedb/blob/5ae5f30ac01591a185d9f795a43773a52ea28852/internal/datastore/postgres/watch.go#L51)), but I did not master the current logic of the algorithm )

Some detail can be found here https://gist.github.com/aberkovsky/4ca8fd7227b83772ba6d3fc19cc18595

**Comment by claraisrael** [comment]
Hello, I'm now facing a similar issue where I'm using Postgres and it hangs on CheckPermission requests. It works fine with WriteRelationships and Read from what I've explored. 
I'm using the latest image (v1.22.0)

**Comment by vroldanbet** [comment]
@claraisrael I think that's unlikely related to this. When some API methods work but Check hangs, it typically suggests an incorrectly configured dispatch. If you are using kubernetes, we recommend using the SpiceDB operator https://github.com/authzed/spicedb-operator

**Comment by claraisrael** [comment]
Thanks Victor! I'll explore deploying to K8s with SpiceDB Operator :)  Is there a way to run automate migrations with postgres? I cant seem to find documentation.

**Comment by vroldanbet** [comment]
@claraisrael I'd suggest moving the conversation to an issue in the operator repo, or to our Discord channel, we usually hang around and answer questions from folks 🙏🏻
