### ISSUE TITLE
Leopard indexing system 

### ISSUE THREAD

**Issue by ecordell** [authzed/spicedb#129]
The Zanzibar paper devotes a lot of time to the leopard cache, which caches member to group and group to group relationships:

> Recursive pointer chasing during check evaluation has difficulty maintaining low latency with groups that are deeply nested or have a large number of child groups. For selected namespaces that exhibit such structure, Zanzibar handles checks using Leopard, a specialized index that supports efficient set computation.

> The Leopard system consists of three discrete parts: a serving system capable of consistent and low-latency operations across sets; an offline, periodic index building system; and an online real-time layer capable of continuously updating the serving system as tuple changes occur.

**Comment by jzelinskie** [comment]
This has been superseded by a concrete proposal: https://github.com/authzed/spicedb/issues/207

**Comment by ecordell** [comment]
The Tiger cache proposal is mostly focused on the reverse direction (lookup), and Leopard Cache is primarily focused on the forward direction.

They could both be provided by the same thing (maybe configured with flags?), but the runtime requirements of a Tiger Cache should be moderately to significantly higher than the Leopard Cache. If Lookups were not part of your critical path you might choose to run Leopard and not Tiger. 

Anyway we might want to resurrect this issue as a feature request on the tiger cache, we can see how it plays out.

**Comment by josephschorr** [comment]
I personally believe this should be a fully isolated system, backed by the Watch API library, but exposing its own API and interface. It will likely also need to run at a different scale than Tiger.
