### ISSUE TITLE
Proposal: Bulk Upload and Download APIs

### ISSUE THREAD

**Issue by jakedt** [authzed/spicedb#1303]
Currently the only way to write data to SpiceDB is with the WriteRelationships API, and the only way to read relationships is the ReadRelationships API. These APIs are designed around OLTP use-cases, and are not suitable for bulk reading and writing of data. Use-cases like backup and restore, and backfill require a large amount of relationships to be accessed at once.

We should explore adding more performant APIs for these bulk operations to facilitate these use cases.

**Comment by josephschorr** [comment]
These APIs are now experimentally exposed via the `experimental` service: https://buf.build/authzed/api/docs/main:authzed.api.v1#authzed.api.v1.ExperimentalService

See https://github.com/authzed/spicedb/pull/1326 and https://github.com/authzed/spicedb/pull/1281

**Comment by pradeepreddy-anantha** [comment]
Hi. Can you please share how to consume method using Java client? 
I  am not finding 'bulkImportRelationships' method on ExperimentalServiceGrpc stub. 

Ex:  experimentalService.bulkImportRelationships(request);

**Comment by vroldanbet** [comment]
You can find an example here: https://github.com/authzed/authzed-java/blob/a8ae90a3f8f008ab6e3ea71299064a7b83938981/src/intTest/java/V1ClientTest.java#L212-L239
