### ISSUE TITLE
ResourceExhausted Error Due to Non-Limited newRevisionsQuery and Uncontrolled Buffer Size

### ISSUE THREAD

**Issue by staskosatkin** [authzed/spicedb#1357]
**Issue Description**

While using the Watch API, I've encountered a `ResourceExhausted` error. This problem can lead to the loss of events and disconnections. The issue seems to arise because the `newRevisionsQuery` lacks a limit, which may result in it returning a vast number of snapshots. Furthermore, the buffer size isn't controlled, and it could easily be smaller than the size of `changeToWrite`. This situation creates a risk to the consistency of changes received from the Watch API.

**Relevant Code Snippets**

https://github.com/authzed/spicedb/blob/6d2e468a14e237a3926853193fda04c65d17fe77/internal/datastore/postgres/watch.go#L31-L35
No limit clause present.

**Potential Overflow:**
https://github.com/authzed/spicedb/blob/6d2e468a14e237a3926853193fda04c65d17fe77/internal/datastore/postgres/watch.go#L93-L103
Here, size of `updates` (buffer) could be easily less than `changeToWrite` size.

**Proposed Solution**
I suggest to add a limit to newRevisionsQuery similar to the buffer size. Secondly, controlling the size of the buffer will allow us to continue watching from any point in time until the revisions weren't deleted by the garbage collector (by default it's 24h and it's really enough). This modification provides a great opportunity to maintain the consistency of the event stream, even during downtime of the Watch API's client.  Here's an example fix:

```
for _, changeToWrite := range changesToWrite {
	changeToWrite := changeToWrite

	for int(pgd.watchBufferLength) <= len(updates) {
		sleep := time.NewTimer(watchOverflowSleep)
		select {
		case <-sleep.C:
			continue
		case <-ctx.Done():
			errs <- datastore.NewWatchCanceledErr()
			return
		}
	}

	select {
	case updates <- &changeToWrite:
		// Nothing to do here, we've already written to the channel.
	default:
		errs <- datastore.NewWatchDisconnectedErr()
		return
	}
}
```
**Additional Context**

The proposed fix should improve the reliability of the watch API.

Thank you for your attention to this matter.

Best regards,
staskosatkin

**Comment by josephschorr** [comment]
@staskosatkin seems reasonable. Would you be willing to open a PR?

**Comment by staskosatkin** [comment]
@josephschorr I'll prepare PR, thanks

**Comment by staskosatkin** [comment]
PR was opened https://github.com/authzed/spicedb/pull/1388

**Comment by staskosatkin** [comment]
@josephschorr I'd signed. If you have any additional questions let me know please. Thanks.

**Comment by vroldanbet** [comment]
@staskosatkin we recently released https://github.com/authzed/spicedb/pull/1707 as part of SpiceDB 1.29.0. This makes the buffers block for a configurable amount of time instead of throwing an error (and thus causing Watch API disconnection). We believe this should help with the issues you've observed, but please feel free to reopen if this problem persists.
