### ISSUE TITLE
Filter RCs from release repositories

### ISSUE THREAD

**Issue by jzelinskie** [authzed/spicedb#1378]
Currently all releases including pre-releases are being published to Fury and Homebrew.
If folks prefer that these channels be exclusively stable releases, we could filter this from being published.

**Comment by DGuhr** [comment]
[Link](https://discord.com/channels/844600078504951838/844600078948630559/threads/1111687590777716756) to discord thread 

my opinion:
* I'd prefer to either have 2 separate streams, one "stable" and one "experimental"
* or to have the RCs filtered out completely from brew. 
* From my PoV, this would provide the best default experience for all users trying out spiceDB.

Basically like this:

| Command | Default Behaviour |
|--------|--------|
| `brew install authzed/tap/spicedb` | Install latest stable |
| `brew upgrade authzed/tap/spicedb` | updates to latest stable |
| `brew upgrade` | upgrades to latest stable | 

Currently, these all point to RC's when you do not use version pinning. I know it's good practice to always specify the version when you really use the product, but for people "just trying spicedb out" this would lead them to potentially unstable versions that may also not be aligned with other tooling versions, e.g. playground capabilities etc.
