### ISSUE TITLE
Support OpenTelemetry collectors

### ISSUE THREAD

**Issue by jzelinskie** [authzed/spicedb#14]
Everything is instrumented using [OpenTelemetry], but Jaeger is the only format exposed by command-line flags.
If it can be made generic enough, this could be upstreamed into [cobrautil].

[OpenTelemetry]: https://opentelemetry.io
[cobrautil]: https://github.com/jzelinskie/cobrautil

**Comment by jzelinskie** [comment]
This is done by using OpenTelemetry collectors, which I'm fairly certain Jaeger is being written to support natively.
Ideally we can just support configuring a collector endpoint and that's all that's necessary from within SpiceDB.

**Comment by jzelinskie** [comment]
Any changes to flags need to be backwards compatible, so any PR that fixes this would have to mark the existing jaeger flags as hidden and introduce new ones.

**Comment by josephschorr** [comment]
@jzelinskie: was this done in https://github.com/jzelinskie/cobrautil/commit/21e5e5d94504b42fba3bf41bcec03248de744b98?

**Comment by jzelinskie** [comment]
The changes to cobrautil have been made, but the SpiceDB still needs to add a new flag for it (because it's not backcompat) and then mark the existing jaeger flag as hidden.

**Comment by jzelinskie** [comment]
@cjs @christroger are either of ya'll still interested in taking this on?

**Comment by cjs** [comment]
Yes we will take care of it. I think we also need to do another PR against cobrautil to fix an issue with getting some OTel parameters from the environment.
