### ISSUE TITLE
CEL Best Practices

### ISSUE THREAD

**Issue by TristonianJones** [authzed/spicedb#1410]
As the CEL maintainer, I thought it would be useful to share the following tips and best practices to improve your experience with CEL:

### Use `DynType` over `AnyType`

The `AnyType` is intended to map to `google.protobuf.Any` and any object type rather than the set of all possible value types. A common gotcha is to use a `AnyType` result as the iteration range on a comprehension. On the CEL side, we intend to advise people against using the `AnyType` since cel-go developers mistake this as equivalent to a Go `any` value which is not the case.

###  Partial Eval

The result of a partial evaluation is not an error, but a `types.Unknown` value. In the following snippet, you can expect the behavior as follows:

```go
out, _, err := prg.Eval(<...>)
// Hard error, no additional data will change the result
if err != nil {
   // terminate evaluation
}
// Partial evaluation result, more data may shift the result to a known value or error
if types.IsUnknown(out) {
  // Expression ids from the AST nodes relevant to the completion of the evaluation
  // are included in the out.(types.Unknown) value.
}
// Success! You've got a known value
return val
```

### Attribute Errors

If your customers are encountering issues with runtime errors during field traversals (such as 'no such attribute'), consider enabling `cel.OptionalTypes()` which will make it simpler to write safe-traversal expressions: https://github.com/google/cel-spec/wiki/proposal-246

Hopefully this helps, and I would be happy to review a PR if you'd like some assistance on best practices with CEL.

Cheers!

-Tristan

**Comment by ecordell** [comment]
@TristonianJones Thanks for reaching out!

@josephschorr is planning to make some updates to our CEL usage tomorrow, we'd love your feedback on that PR when it's available.

**Comment by josephschorr** [comment]
@TristonianJones Can you provide some further guidance on the partial evaluation handling? Right now we handle this case by parsing the error message string (yes, its ugly): https://github.com/authzed/spicedb/blob/main/pkg/caveats/eval.go#L115

I tried changing the above to the latest version of CEL and the code to check `types.IsUnknown`, but it is returning false and I'm still receiving an error indicating that the attribute does not exist.

Do I perhaps need to turn off `celopts = append(celopts, cel.EvalOptions(cel.OptPartialEval))`?

Also: where is `OptionalTypes` defined? I don't see it in the `cel.` options list

**Comment by TristonianJones** [comment]
@josephschorr thanks for the ping.

As of CEL v0.13.0, you can [enable OptionalTypes](https://pkg.go.dev/github.com/google/cel-go/cel#OptionalTypes) with the option referenced in the link. 

In terms of the `types.IsUnknown` call, it might help to think about whether the expression would always error, or whether more information might change from an error to a non-error.  Based on what you're describing, it's possible no additional information would change the outcome and thus, you're receiving an error rather than an unknown value. I'll try to put together a repro in the next couple days to illustrate how partial eval is intended to work. I realize it's not well-documented.

-Tristan

**Comment by TristonianJones** [comment]
@josephschorr it looks like there's a somewhat simple misconfiguration related to a sharp edge with configuring partial evaluation. I've added a new interface to provide the information you're looking for: https://github.com/google/cel-go/pull/766

That said, next week I'll be updating `types.Unknown` to include the missing attributes: https://github.com/google/cel-go/issues/771. Once that's in, you'll be able to do partial evaluation with the `types.Unknown` returning the data which the code currently returns to callers.

**Comment by josephschorr** [comment]
@TristonianJones Excellent! Looking forward to being able to use it! Thanks for all the support

**Comment by TristonianJones** [comment]
@josephschorr The latest [cel-go v0.17.1](https://github.com/google/cel-go/releases/tag/v0.17.1) includes the changes that you need to update and preserve the existing user experience.

Instead of `cel.PartialVars`, use the environment instance to infer the partial vars based on the presence (or absence) of top-level variables in the input: `env.PartialVars(input)`.

If you do this, the `types.IsUnknown()` check will yield `true` when a missing attribute is relevant to the completion of the evaluation. The `types.Unknown` values exposes methods to get the expression ids and the associated attribute trails (which nicely render to strings).

Let me know if you need any help with the CEL bump and review.

**Comment by josephschorr** [comment]
@TristonianJones excellent. Will take a look tomorrow

**Comment by josephschorr** [comment]
@TristonianJones https://github.com/authzed/spicedb/pull/1451 is ready for your review!
