### ISSUE TITLE
Caveat

### ISSUE THREAD

**Issue by IFpop** [authzed/spicedb#1432]
Sorry, I am learning about SpiceDB, I usually see caveat in code, but I really don't understand what the caveat do in SpiceDB.
Could you please tell how to get the annswer?

**Comment by zzzzzzian-20** [comment]
I‘m no expert but after using spicedb for over a year, I deem caveat as a way of customization of **conditional** relationship with which the system could automatically judge whether a certain relation is valid provided with **context** like current timestamp or other **variables**

**Comment by vroldanbet** [comment]
@IFpop did the documentation in https://authzed.com/docs/reference/caveats not help?
