### ISSUE TITLE
Playground "Test Relationships" syntax highlighting breaks on usersets

### ISSUE THREAD

**Issue by jwineinger** [authzed/spicedb#1454]
When I use a subject reference with relation (userset from zanzibar) in the Test Relationships tab on the playground in text mode (vs table), the syntax highlighting seems to break until after an empty line.

![Screenshot 2023-07-21 at 9 01 40 AM](https://github.com/authzed/spicedb/assets/287161/047e091d-b6f5-469e-a7a2-a1724d69c4eb)

Now adding an empty line restores the highlighting.

![Screenshot 2023-07-21 at 9 01 47 AM](https://github.com/authzed/spicedb/assets/287161/899d101e-dcd1-47a5-ab13-437140cb8c8a)

And for good measure, adding the empty line later on

![Screenshot 2023-07-21 at 9 05 49 AM](https://github.com/authzed/spicedb/assets/287161/2d5ccceb-cc8d-4951-9823-1548d5c02db4)

**Comment by jakedt** [comment]
Documenting here: this also occurs with subject wildcards.
