### ISSUE TITLE
Improve error messages on datastore transaction abort

### ISSUE THREAD

**Issue by TimDiekmann** [authzed/spicedb#1525]
### What platforms are affected?

macos

### What architectures are affected?

arm64

### Steps to Reproduce

I have a situation where multiple relations are modified/deleted at the same time. I was able to reproduce the behavior with this schema:
```
definition user {}

definition entity {
    relation viewer: user
}
```

I have two threads, one thread creates the tuples 
```
entity:A#viewer@user:alice
entity:B#viewer@user:alice
```
and the other thread is creating 
```
entity:C#viewer@user:bob
entity:D#viewer@user:bob
```

_UPDATE: Even with only a single relation per thread the same behavior happens_

After the threads finish their work they will immediately remove the relations again. All tuples are passed in a batch, so in total there are two creation and two deletion statements.

### Expected Result

I expect that the deletion of the relationships will succeed.

### Actual Result

The deletion in one thread error with a `commit unexpectedly resulted in rollback` error. The corresponding Postgres log is
```
ERROR:      could not serialize access due to read/write dependencies among transactions
DETAIL:     Reason code: Canceled on identification as a pivot, during write.
HINT:       The transaction might succeed if retried.
STATEMENT:  UPDATE relation_tuple SET deleted_xid = $1 WHERE deleted_xid = $2 AND (namespace = $3 AND object_id = $4 AND relation = $5 AND userset_namespace = $6 AND userset_object_id = $7 AND userset_relation = $8 OR namespace = $9 AND object_id = $10 AND relation = $11 AND userset_namespace = $12 AND userset_object_id = $13 AND userset_relation = $14) RETURNING namespace, object_id, relation, userset_namespace, userset_object_id, userset_relation
```
The output of `spicedb`:
```
INF finished call grpc.code=OK grpc.component=server grpc.method=WriteRelationships grpc.method_type=unary grpc.service=authzed.api.v1.PermissionsService grpc.start_time=2023-09-04T15:29:00Z grpc.time_ms=8.843 peer.address=127.0.0.1:41190 protocol=grpc requestID=c7a99584b165420c9aa5ff580476310f
INF finished call grpc.code=OK grpc.component=server grpc.method=WriteRelationships grpc.method_type=unary grpc.service=authzed.api.v1.PermissionsService grpc.start_time=2023-09-04T15:29:00Z grpc.time_ms=14.573 peer.address=127.0.0.1:41202 protocol=grpc requestID=8751db177bd767b4c1297c6699462c34
INF finished call grpc.code=OK grpc.component=server grpc.method=WriteRelationships grpc.method_type=unary grpc.service=authzed.api.v1.PermissionsService grpc.start_time=2023-09-04T15:29:00Z grpc.time_ms=3.775 peer.address=127.0.0.1:41190 protocol=grpc requestID=0db37171a0c164666995d7b5156c2cb2
ERR received unexpected error error="commit unexpectedly resulted in rollback" requestID=107f3e0d909ce64b407474144226d552
ERR finished call grpc.code=Unknown grpc.component=server grpc.error="commit unexpectedly resulted in rollback" grpc.method=WriteRelationships grpc.method_type=unary grpc.service=authzed.api.v1.PermissionsService grpc.start_time=2023-09-04T15:29:00Z grpc.time_ms=5.34 peer.address=127.0.0.1:41190 protocol=grpc requestID=107f3e0d909ce64b407474144226d552
```

The error suggests that both transactions attempting to update the same relation tuple but this seems wrong as the tuples are completely distinct. 

How I'm able to mitigate this? Am I supposed to retry the operations on failure? Or is my Postgres instance misconfigured? Or is this a bug in the SpiceDB client?

Any help would be much appreciated, I'm happy to provide further information if needed.

**Comment by josephschorr** [comment]
> After the threads finish their work they will immediately remove the relations again

If you are using this as a testing system, it is recommended to not run against a real SpiceDB, but instead use `serve-testing`: https://authzed.com/docs/guides/validation-and-testing#making-api-calls

> The error suggests that both transactions attempting to update the same relation tuple but this seems wrong as the tuples are completely distinct.

They aren't distinct over the `relation`, however, and that is causing Postgres to lock to ensure that consistent ordering is maintained

> How I'm able to mitigate this? Am I supposed to retry the operations on failure? Or is my Postgres instance misconfigured? Or is this a bug in the SpiceDB client?

You are likely overloading your Postgres instance by constantly writing and deleting against the same relation. You can usually mitigate this by scaling your instance vertically, but if this is indeed a means of testing, `serve-testing` is the better solution

**Comment by TimDiekmann** [comment]
`serve-testing` sounds like something I like to use, Yes, thank you! 

> You are likely overloading your Postgres instance

How easily can this actually happen in production if this behavior already happens with only two creations/deletions? Is it recommended just to retry the operation if this happens? If so, would it be possible to make this a named error? Currently, the gRPC interface returns a `2` as an error code. Maybe `15` (`DataLoss`) would be more suitable?

**Comment by josephschorr** [comment]
Well, its not dataloss - a transaction is not considered applied unless, well, it is applied successfully.

It can certainly happen in production if you're making many writes per second on a reasonable sized Postgres instance, but not before that point

**Comment by williamdclt** [comment]
> Am I supposed to retry the operations on failure

Pretty much yeah. Writing to any system can fail: here it's due to Postgres but it could have been anything else (eg an unreliable network). If you need to ensure consistency between SpiceDB and your own database, you'll need use something like an outbox pattern (or to figure out how to implement 2-phase commit with SpiceDB).

That being said, it would be great if spicedb exposed some clearer logs for this case: "commit unexpectedly resulted in rollback" isn't super helpful, esp with a response code 2 (UNKNOWN). It's basically the equivalent of a 500 "something went wrong". Unserializable transactions are pretty common in my experience (depending on write patterns of course) and to be expected: maybe a GRPC status 10 would also be more appropriate?

**Comment by TimDiekmann** [comment]
Yeah, I think `10` would be a good fit. Basically every error code would be better as it would not be a generic "something went wrong" error.

**Comment by josephschorr** [comment]
I believe this was addressed most recently by https://github.com/authzed/spicedb/commit/a4cc96534bf2e80ab1c90871553ecd80bbdbd0f5: it returns gRPC code `10` and a specialized error reason.

Feel free to reopen if this issue was not fully addressed
