### ISSUE TITLE
Comments in SpiceDB schema are only added/updated if the underlying definition has changed

### ISSUE THREAD

**Issue by alekov87** [authzed/spicedb#1533]
### What platforms are affected?

linux

### What architectures are affected?

others

### Steps to Reproduce

Hey team, playing with schemas I've found a bug. 

To reproduce:

1. write the following schema into the instance
```
definition user {}
```

All good. `zed schema read` returns the above schema.

2. add another definition to it with a comment and write the schema
```
definition user {}

// it's a role
definition role {}
```
All good. `zed schema read` returns the above schema.

3. add comment to the first definition and write the schema
```
// it's a user
definition user {}

// it's a role
definition role {}
```

NOT good. `zed schema read` returns the schema from step 2. New comment is not written into the schema.
In fact the comment is only added/updated if the underlying definition has changed.

### Expected Result

after step 3 `zed schema read` is expected to return 

```
// it's a user
definition user {}

// it's a role
definition role {}
```

### Actual Result

```
definition user {}

// it's a role
definition role {}
```

**Comment by josephschorr** [comment]
This is because SpiceDB is doing a *structural* diff and skipping writing any definitions that have not changed structurally. We'll need to have the comments included in the diff for them to be updated
