### ISSUE TITLE
Panic on giving ZedTokens from CRDB to Postgres

### ISSUE THREAD

**Issue by josephschorr** [authzed/spicedb#1539]
When giving a ZedToken that was created by CRDB-backed SpiceDB to a Postgres-backed SpiceDB, a panic can be raised if the ZedToken contains a timestamp that is too large for Postgres to handle

This should instead return an error.

Thanks to `Duncan` in Discord for reporting (https://discord.com/channels/844600078504951838/1153638230051270698)

**Comment by DBBrowne** [comment]
Thanks for opening this up so fast.
