### ISSUE TITLE
MySql some queries missing an index

### ISSUE THREAD

**Issue by nulian** [authzed/spicedb#1543]
Not sure what call in spicedb does it but it generated a query like below which is fairly slow because it came up in our slow query log because created_transaction is missing an index in the MySQL version of it.

```
SELECT namespace, object_id, relation, userset_namespace, userset_object_id, userset_relation, caveat_name, caveat_context, created_transaction, deleted_transaction FROM relation_tuple WHERE ((created_transaction > 158582 AND created_transaction <= 158583) OR (deleted_transaction > 158582 AND deleted_transaction <= 158583));
```

### Expected Result

All queried columns having an index.

### Actual Result

Fast lookup query

**Comment by josephschorr** [comment]
@nulian Be curious to see an `EXPLAIN` output from your database, just so we can compare to ours

**Comment by nulian** [comment]
Not precisly the same database but is a based on a dump from it but this is the explain
Without index it takes somewhere between 500ms and 5s
With index it's 10ms - 150ms

```
|id|select_type|table|type|possible_keys|key|key_len|ref|rows|Extra|
|--|-----------|-----|----|-------------|---|-------|---|----|-----|
|1|SIMPLE|relation_tuple|ALL|ix_relation_tuple_by_deleted_transaction||||224739|Using where|

```

**Comment by vroldanbet** [comment]
@nulian are you using the `Watch` API? Would you mind sharing the index you added?

This access pattern seems to be used by the MySQL datastore Watch API implementation:

https://github.com/authzed/spicedb/blob/8f6136b6f45b155caa665fd4b47bf492ae95acc7/internal/datastore/mysql/watch.go#L94-L103

this is the explain I got initially with 84K rows:

| EXPLAIN                                                                                                                                                                                                                                                                                                                                                                                          |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| -> Filter: (((relation_tuple.created_transaction > 158582) and (relation_tuple.created_transaction <= 158583)) or ((relation_tuple.deleted_transaction > 158582) and (relation_tuple.deleted_transaction <= 158583)))  (cost=7920 rows=16334) (actual time=71.3..71.3 rows=0 loops=1)
    -> Table scan on relation_tuple  (cost=7920 rows=77839) (actual time=0.0697..58.1 rows=84849 loops=1)
 |

Then I added the following index, the rows scanned where lower:

```sql
CREATE INDEX ix_watch
    ON relation_tuple (created_transaction, deleted_transaction DESC);
```

OR

```sql
CREATE INDEX ix_watch
    ON relation_tuple (created_transaction DESC, deleted_transaction DESC);
```

| EXPLAIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| -> Filter: (((relation_tuple.created_transaction > 158582) and (relation_tuple.created_transaction <= 158583)) or ((relation_tuple.deleted_transaction > 158582) and (relation_tuple.deleted_transaction <= 158583)))  (cost=0.804 rows=1) (actual time=0.0921..0.0921 rows=0 loops=1)
    -> Sort-deduplicate by row ID  (cost=0.804 rows=1) (actual time=0.0902..0.0902 rows=0 loops=1)
        -> Index range scan on relation_tuple using ix_watch over (158582 < created_transaction <= 158583)  (cost=1.11 rows=1) (actual time=0.0387..0.0387 rows=0 loops=1)
        -> Index range scan on relation_tuple using ix_relation_tuple_by_deleted_transaction over (158582 < deleted_transaction <= 158583)  (cost=0.36 rows=1) (actual time=0.0342..0.0342 rows=0 loops=1)
 |


| EXPLAIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| -> Filter: (((relation_tuple.created_transaction > 158582) and (relation_tuple.created_transaction <= 158583)) or ((relation_tuple.deleted_transaction > 158582) and (relation_tuple.deleted_transaction <= 158583)))  (cost=0.804 rows=1) (actual time=0.104..0.104 rows=0 loops=1)
    -> Sort-deduplicate by row ID  (cost=0.804 rows=1) (actual time=0.102..0.102 rows=0 loops=1)
        -> Index range scan on relation_tuple using ix_watch over (158583 <= created_transaction < 158582)  (cost=1.11 rows=1) (actual time=0.0759..0.0759 rows=0 loops=1)
        -> Index range scan on relation_tuple using ix_relation_tuple_by_deleted_transaction over (158582 < deleted_transaction <= 158583)  (cost=0.36 rows=1) (actual time=0.00633..0.00633 rows=0 loops=1)
 |

**Comment by nulian** [comment]
yeah am using the watch api. 
Just added a simple index only on that field so the combined indexes probably would be better you came up with.

**Comment by vroldanbet** [comment]
@nulian perfect then I'll open a PR with the new proposed index
