### ISSUE TITLE
[memdb] Sending multiple concurrent write relationship requests silently fails 

### ISSUE THREAD

**Issue by svenefftinge** [authzed/spicedb#1545]
### What platforms are affected?

linux

### What architectures are affected?

amd64

### Steps to Reproduce

Start spicedb in `serve-testing` mode
Send 200 writeRelationship requests in parallel. 

### Expected Result

either error responses or ok-reponses and relationships are written successfully

### Actual Result

The requests are responded OK. but are actually not written. The spciedb process logs 
```
1:37PM ERR received unexpected error error="serialization error"
1:37PM ERR received unexpected error error="serialization max retries exceeded"
```

**Comment by vroldanbet** [comment]
@svenefftinge what size does the `WriteRelationshipRequest` have, one single relationship?
Do the logs shared here indicate that while SpiceDB logs an error on the server-side, a gRPC code `OK` is returned to the client? What does the SpiceDB log for the response look like?

Which SpiceDB version is this?

**Comment by josephschorr** [comment]
@svenefftinge I'm looking into why the error is not returned to the caller, but getting additional information about scale and usage would certainly be helpful

**Comment by josephschorr** [comment]
@svenefftinge I've verified that the datastore is correctly raising the error to the API call, so it shouldn't be failing silently. I've issued a PR to make the error nicer and contain more explaination
