### ISSUE TITLE
`BulkCheckPermission` does not return results in the same order as requests

### ISSUE THREAD

**Issue by tadejsv** [authzed/spicedb#1563]
### What platforms are affected?

linux, macos, windows

### What architectures are affected?

amd64, arm64

### Steps to Reproduce

I have noticed that in some cases, `BulkCheckPermission` returns the results (permissions) in a different order than requests.

### Expected Result

I think the desired behavior would be to return results in the same order as requests

### Actual Result

-

**Comment by josephschorr** [comment]
@tadejsv This is by design: The bulk check permissions has a streaming response and will returns results as they are computed; this is why each returned result contains a `pair` that includes the initial request: to ensure it can be correlated with the request that created the response

**Comment by tadejsv** [comment]
But it doesn't actually have a streaming response?

**Comment by tadejsv** [comment]
@josephschorr https://github.com/authzed/api/blob/main/authzed/api/v1/experimental_service.proto#L48

**Comment by josephschorr** [comment]
I guess that was changed at some point... we can look into reordering the response then, although the intent is still to use the request information from the pairs for correlation, not the order

**Comment by bradengroom** [comment]
+1 to ordered results. It makes the APIs really ergonomic from the client's perspective. 

```
# pseudocode
resources = resources_to_check = [...]
responses = spiceDB.bulk_check(resources)
authorized_resources = [
    resource
    for resource, response in zip(resources, responses)
    if response  # filter down to access granted
]
```
