### ISSUE TITLE
Missing spans from trace for v1.PermissionsService/LookupResources

### ISSUE THREAD

**Issue by wthornton1** [authzed/spicedb#1662]
### What platforms are affected?

linux

### What architectures are affected?

amd64

### What SpiceDB version are you using?

v1.27.0

### Steps to Reproduce

1. Make an authzed.api.v1.PermissionsService/LookupResources request 
2. Collect the traces from spicedb

### Expected Result

All or most of the excution time should be accounted for, and should include the fan out via dispatch. 

### Actual Result

Approximately ~90% of the total execution time seems to be be missing

<img width="858" alt="Screenshot 2023-11-27 at 19 49 18" src="https://github.com/authzed/spicedb/assets/142009465/c7ad4210-6211-4733-8b1e-2d960cd4ca4f">

**Comment by vroldanbet** [comment]
@wthornton1 can you specify which datastore are you using?

**Comment by wthornton1** [comment]
Currently using postgres 15.3 - I can edit the issue description if you want

**Comment by wthornton1** [comment]
Is there anyway to put some kind of overarching parent trace? ie. collecting responses or something of ths sort

**Comment by vroldanbet** [comment]
@wthornton1 I didn't spend a lot of time into it but I couldn't figure out a way to aggregate this in a visually-compelling way. Different parts of the reachability graph are evaluated concurrently and the whole pipeline works async, so responses are published as they become available. It always led to a completely unusable trace with lots of small pieces. I'm going to summon @josephschorr with the hope he can suggest an approach to make those traces more usable.

**Comment by josephschorr** [comment]
I've tried doing so myself, and run into the exact same problem

**Comment by DBBrowne** [comment]
Thank you both - having confirmation about what that blank time is is helpful.

**Comment by vroldanbet** [comment]
We recently found that OTel client-side streaming interceptors weren't being installed, which meant that in an actual SpiceDB cluster spans from `LookupResources` traces wouldn't show up.

This has been fixed in https://github.com/authzed/spicedb/pull/1836, which instruments OTel using the new gRPC stats API for this.

**Comment by DBBrowne** [comment]
fantastic, thanks!

Happily, spicedb has been rock solid for us since November.  python gRPC, not so much.
