### ISSUE TITLE
Makes the max receive size of grpc to be configurable

### ISSUE THREAD

**Issue by karlwang1983** [authzed/spicedb#1703]
### Problem Statement

We want to support multi-tenants with spicedb and I took a look at https://github.com/authzed/spicedb/issues/204. There would be more than 2k tenants in our environment, so we defined 2k different namespaces with tenant Id. However, we found the total size of schema is more than 5M but the default max receive size of grpc is 4M. We got the error as below. Is there a way to make the max size value to be configurable?
`grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "grpc: received message larger than max (5840003 vs. 4194304)"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:50051 {created_time:"2024-01-04T13:33:08.265374+08:00", grpc_status:8, grpc_message:"grpc: received message larger than max (5840003 vs. 4194304)"}"`

### Solution Brainstorm

Makes the max receive size of grpc to be configurable

**Comment by karlwang1983** [comment]
Supports appending schema or makes the max receive size configurable.

**Comment by corkrean** [comment]
Is it sufficient enough isolation for you to represent each tenant as an object in the graph? e.g. `definition tenant { member: user}`

**Comment by karlwang1983** [comment]
Thanks for your comments, @corkrean. But it's probably not meet our requirement since each tenant has some special internal user who has same Ids. We can not just identify them by user Id. The other issue is sometime we need to migrate a tenant data from a region to another. This way will cause migration more complex.

**Comment by corkrean** [comment]
> But it's probably not meet our requirement since each tenant has some special internal user who has same Ids. 
One solution to this is to prefix each user id with the tenant id e.g. `user:tenant9_user123`

> The other issue is sometime we need to migrate a tenant data from a region to another. This way will cause migration more complex.
Prefixing the user IDs with the tenant IDs would indeed make this more complex.

**Comment by karlwang1983** [comment]
> > But it's probably not meet our requirement since each tenant has some special internal user who has same Ids.
> 
> One solution to this is to prefix each user id with the tenant id e.g. `user:tenant9_user123`
> 
> > The other issue is sometime we need to migrate a tenant data from a region to another. This way will cause migration more complex.
> 
> Prefixing the user IDs with the tenant IDs would indeed make this more complex.

Yes, this is a way if we don't want to support exposing grpc max size setting.

**Comment by corkrean** [comment]
@ashish-ema I'm curious why your schema is so large; but this issue isn't a good place to discuss that. Please mention me in a GitHub discussion post, and we'll continue the conversation there for now.

**Comment by ydmztang** [comment]
@corkrean We had similar issue.
I'm surprised that there is no API to operate on a particular namespace, but only the entire schema, so I have to deal with a huge schema when there are too many tenants, or I'll have to prefix the object/subject instead of prefix the namespace.

I bet there were reasons it's designed like this. However, I wonder if there will be performance difference prefixing namespace vs prefix the object/subject. We are using MySql for now and has plan to switch to CockroachDB if the business justifies.

**Comment by blainetanner** [comment]
Hey @ydmztang there's a few ways we can handle this. Ping me at blaine.tanner@authzed.com and we can set up a chat to get it squared away.

**Comment by josephschorr** [comment]
> I'm surprised that there is no API to operate on a particular namespace, but only the entire schema, so I have to deal with a huge schema when there are too many tenants, or I'll have to prefix the object/subject instead of prefix the namespace.

For reference, there was, and it made it impossible for SpiceDB to effectively do certain kinds of type checking and optimizations. We decided to move away from that design to a singular schema operation for safety and better read performance.
