### ISSUE TITLE
Change unable to init telemetry `error` to `warning` since it is not strict dependency to SpiceDB

### ISSUE THREAD

**Issue by reza-ebrahimi** [authzed/spicedb#1716]
### What platforms are affected?

linux

### What architectures are affected?

amd64

### What SpiceDB version are you using?

Latest docker image

### Steps to Reproduce

Having no telemetry, as far as I know.

```
spicedb_1  | {"level":"error","error":"unable to initialize telemetry collector: unable to query DB stats: unable to query unique ID: no rows in result set","time":"2024-01-18T12:05:32Z","message":"terminated with errors"}
```

### Expected Result

Is should be a `warning`. In some cases (for local development) there is no need for telemetry.

### Actual Result

It is an `error`.

**Comment by vroldanbet** [comment]
While I agree the telemetry is not a hard requirement in development environment (although it helps the team immensely understand adoption, even in development), the fact it fails to start could indicate something else is gone wrong with the datastore, as it is in an unexpected state.

**Comment by josephschorr** [comment]
@vroldanbet Agreed. We should change the error into a warning but as the error does indicate a problem, we should move the check into datastore startup and still fail (with a proper error message)

I'll prep a change
