### ISSUE TITLE
Not able to import BulkCheckPermission

### ISSUE THREAD

**Issue by satishTeachmint** [authzed/spicedb#1728]
### What platforms are affected?

macos

### What architectures are affected?

others

### What SpiceDB version are you using?

0.12.0

### Steps to Reproduce

while importing the following module I'm not able to import those. as they are not defined in __init__ in _authzed/api/v1/__init__.py_.

```
from authzed.api.v1 import (
    BulkCheckPermissionRequest,
    BulkCheckPermissionResponse,
    BulkCheckPermissionRequestItem,
)
```
even though I define it gives the below error. Please resolve this error.
```
  File "spicedb_apis.py", line 193, in bulk_permission_check
    resp = client.BulkCheckPermission(BulkCheckPermissionRequest(items=permisions_array))
AttributeError: 'Client' object has no attribute 'BulkCheckPermission'
```

### Expected Result

I can use the following code properly
`resp = client.BulkCheckPermission(BulkCheckPermissionRequest(items=permisions_array))`

### Actual Result

getting below error 
```
Traceback (most recent call last):
  File "spicedb_apis.py", line 1, in <module>
    from authzed.api.v1 import (
ImportError: cannot import name 'BulkCheckPermissionRequest' from 'authzed.api.v1' (/Users/satishnaidu/Documents/GitHub/spiceDb/env/lib/python3.7/site-packages/authzed/api/v1/__init__.py)
```

**Comment by vroldanbet** [comment]
@satishTeachmint 👋🏻 which versions of SpiceDB and `authzed-py` are you using? The report indicates SpiceDB `0.12.0`, which I assume is not right and you are referring to `authzed-py`.

We have some [example tests](https://github.com/authzed/authzed-py/blob/98e992171089c3b65e2c708a215947ac111c4562/tests/v1_test.py#L191-L221) in the `authzed-py` repo, does that help?
