### ISSUE TITLE
BulkImport request caveat context error

### ISSUE THREAD

**Issue by ryaneorth** [authzed/spicedb#1862]
### What platforms are affected?

others

### What architectures are affected?

others

### What SpiceDB version are you using?

v1.30.1 (SpiceDB Dedicated)

### Steps to Reproduce

Use the bulk API to import greater than 5000 relationships at a time (note relationships do not have caveats specified)

### Expected Result

Bulk Import Succeeds

### Actual Result
```
COPY from stdin failed: rpc error: code = InvalidArgument desc = request caveat context should have less than 1000000 bytes but had 1168509 (SQLSTATE 57014)
```

**Comment by ryaneorth** [comment]
Note this only happens when you call `.Send(...)` with greater than ~5000 relationships.

**Comment by corkrean** [comment]
This is coming from Fine Grained Access Management, an Enterprise SpiceDB feature. Authzed is tracking this issue internally.

**Comment by vroldanbet** [comment]
Fix is up https://github.com/authzed/internal/pull/5582
