### ISSUE TITLE
brew install authzed/tap/zed returning error

### ISSUE THREAD

**Issue by ayushgupta2959** [authzed/spicedb#1910]
### What platforms are affected?

macos

### What architectures are affected?

amd64, arm64

### What SpiceDB version are you using?

N/A

### Steps to Reproduce

command `brew install authzed/tap/zed`

### Expected Result

fix the brew install error

### Actual Result

<img width="673" alt="Screenshot 2024-05-23 at 12 48 13 PM" src="https://github.com/authzed/spicedb/assets/37008291/5c58873f-b600-4d72-8515-c4af7151dc84">

**Comment by vroldanbet** [comment]
@ayushgupta2959 sorry I realized you meant `zed`, please open in the zed repository
