### ISSUE TITLE
Rename Datastore Revision() method

### ISSUE THREAD

**Issue by jzelinskie** [authzed/spicedb#192]
A new name should more accurately represent the intention of the method.

CRDB datastores uses a quantized time as the revision, while Postgres/Memory datastores use random fuzzing to determine their revision

**Comment by jzelinskie** [comment]
@yuchen-sun are you still interested in taking this on?

**Comment by yuchen-sun** [comment]
> @yuchen-sun are you still interested in taking this on?

yeah, I was looking at the previously mentioned papers and studies oidc.

Of course, if you have an arrangement, you can always remove me from the program

**Comment by jzelinskie** [comment]
We realized that "QuantizedRevision" is not a universally better name because that's not how each datastore uses it.
I moved the state of this issue back to "needs discussion" as a result of this realization.
