### ISSUE TITLE
Allow credential JSON for Spanner options

### ISSUE THREAD

**Issue by lexcao** [authzed/spicedb#1941]
### Problem Statement

I am using SpiceDB library mode with Spanner for testing.
And I want to pass `CredentialsJSON` for Spanner.

### Solution Brainstorm

Add `credentialsJSON` for `spannerOptions`

I will send a PR.

**Comment by miparnisari** [comment]
Heads up @lexcao, we will likely remove support for this in the next release. See https://github.com/authzed/spicedb/pull/3038

**Comment by tstirrat15** [comment]
Though before I go and merge that - is there a reason that Application Default Credentials don't work in your context?

**Comment by lexcao** [comment]
Hi @miparnisari, thanks for reaching out to me for this.

---
Hi @tstirrat15, We use SpiceDB in library mode with Cloud Spanner. Since our environment does not provide Application Default
  Credentials (ADC), we manage Spanner credentials through remote configuration. For example, when the server
  starts, it loads a Google Cloud service account from remote config to initialize the Spanner client.

So I need to provide a way to initialize Spanner directly from a service account JSON when using library mode. I
  hope this capability remains available as long as library mode is supported.
