### ISSUE TITLE
OptionalConcreteLimit and OptionalCursor on LookupSubjects doesn't work.

### ISSUE THREAD

**Issue by karlwang1983** [authzed/spicedb#1964]
### What platforms are affected?

macos

### What architectures are affected?

arm64

### What SpiceDB version are you using?

v1.33.0

### Steps to Reproduce

1 Create 10 editor relations of user and documents.
2 Invoke LookupSubject API with subject request:
` LookupSubjectsRequest
                {
                    Resource = "document1",
                    SubjectObjectType = "user",
                    Permission = "editor",
                    Consistency = new SpiceDB.Consistency
                    {
                        FullyConsistent = true
                    },
                    OptionalConcreteLimit = 2,
                    OptionalCursor = null
                };
`
3 Expect return 2 subjects.
4 Actually return 10 subjects, after_result_cursor is null.

### Expected Result

Expect return 2 subjects

### Actual Result

Actually return 10 subjects, after_result_cursor is null.

**Comment by vroldanbet** [comment]
Hey @karlwang1983, support for cursors in `LookupSubjects` is not yet merged: https://github.com/authzed/spicedb/pull/1379

This is an artifact of the API being published, and already merged into `spicedb` but the actual implementation not being in place.

https://github.com/authzed/spicedb/pull/1379 is already reviewed, we are conducting more tests, and should be planned for 1.35.

FYI @josephschorr

**Comment by karlwang1983** [comment]
@vroldanbet  Thank you for your prompt reply.  Looking forward to the release of the version 1.35
