### ISSUE TITLE
Proposal: Health check endpoint for HTTP API

### ISSUE THREAD

**Issue by BraedonLeonard** [authzed/spicedb#1969]
### Problem Statement

The gRPC API has a health check endpoint, but the HTTP API has no equivalent. Adding a basic health check endpoint such as `GET /v1/health` which doesn't require authentication headers would be a useful equivalent.

**Comment by vroldanbet** [comment]
The health endpoint is already available at `/healthz`

**Comment by BraedonLeonard** [comment]
Thanks for you the quick response. Is there any documentation for this endpoint? I didn't see it in the HTTP API reference: https://www.postman.com/authzed/workspace/spicedb/overview

**Comment by BraedonLeonard** [comment]
Good to know, thanks!

**Comment by vroldanbet** [comment]
@BraedonLeonard I've updated the postman examples with the health endpoint
