### ISSUE TITLE
--datastore-bootstrap-overwrite is additive, not overwriting previous namespaces

### ISSUE THREAD

**Issue by OumaimaBenGhedifa** [authzed/spicedb#1982]
When using the `--datastore-bootstrap-overwrite` flag, the expected behavior is that the datastore should be completely overwritten with the new data from the bootstrap file. However, the current behavior is additive, meaning it leaves the previous namespaces intact and adds the new ones from the bootstrap file. This can lead to unexpected results and potential conflicts.
**Example**
Initial Schema (Before Overwrite) : 
```
Definition user {}

Definition document {
    relation writer: user

    permission write = writer
}
```
Bootstrap File (For Overwrite)

```
Definition user {}

Definition article {
    relation reader: user

    permission read = reader 
}
```
**Expected Behavior**
The datastore should be entirely overwritten with the namespaces from the bootstrap file, and previous namespaces should be removed.

```
Definition user {}

Definition article {
    relation reader: user

    permission read = reader 
}
```
**Actual Behavior**
The datastore retains the previous namespaces and adds the new ones from the bootstrap file, resulting in an additive behavior.
```
Definition user {}

Definition document {
    relation writer: user

    permission write = writer
}

Definition article {
    relation reader: user

    permission read = reader 
}
```

**Comment by ecordell** [comment]
I suspect that the bootstrap schema writer is using the old (v1apha1) schema write instead of the new (v1) schema write.
