### ISSUE TITLE
wildcard support

### ISSUE THREAD

**Issue by pathing** [authzed/spicedb#1996]
### Problem Statement

In api authentication, wildcard authentication is often required, for example, resource:/api/v1/user/*#access@user:testuser

Then the user: testuser will has the resource: /api/v1/user/user access permissions

Or is there any other way to achieve this scenario

**Comment by vroldanbet** [comment]
👋🏻 My apologies but I'm having difficulties to parse this request. Please try to reframe the question

**Comment by josephschorr** [comment]
@pathing If you're asking if you can link a subject to *all* resources of a type, the answer is no. See: https://github.com/authzed/spicedb/issues/346 for why this will likely not be supported; instead, we will likely support static relationships: https://github.com/authzed/spicedb/issues/1266

**Comment by pathing** [comment]
> @pathing If you're asking if you can link a subject to _all_ resources of a type, the answer is no. See: #346 for why this will likely not be supported; instead, we will likely support static relationships: #1266

Thanks for your reply. But what I need to support is that the resource id has a definite prefix and a * representing all resources that support a particular prefix
@josephschorr

**Comment by josephschorr** [comment]
@pathing if your goal is to handle the prefix yourself, you can just encode a representation of a wildcard. Otherwise, take a look at this proposal: https://github.com/authzed/spicedb/issues/1266
