### ISSUE TITLE
Would it be possible to use SpiceDB with sqlite/libsql?

### ISSUE THREAD

**Issue by AdamJSoftware** [authzed/spicedb#1999]
### Problem Statement

I've been looking at lightweight databases and sqlite, especially libsql has had some very interesting development throughout the years. Would implementing an SQLite data store be practical/in the scope of this project?

**Comment by vroldanbet** [comment]
@AdamJSoftware I can see use for SQLite for scenarios, and I can't think of a reason why it wouldn't be technically possible so long SQLite provides strong consistency. The main challenge is that SpiceDB is scaled horizontally, and adding new nodes that use SQLite will not share the same state. But if your goal is to have a single SpiceDB node that is persistent and easy to run, SQLite would seem like a good fit.

**Comment by vroldanbet** [comment]
@verdverm 👋🏻 I spent some time reading about Cloudflare's D1 and its read-replica support, and I think it's a fascinating product. 

Based on the consistency model offered (_sequential_), you won't be able to address the new enemy problem. That does not mean you can't run SpiceDB if the database does not offer _strict serializable_ consistency: it only means you won't be able to beat the new enemy problem. However, you can still build useful applications without it, so long as you provide the _read-your-writes_ property.

D1's `bookmarks` are a perfect fit for implementing ZedTokens and honoring semantics like `at_least_as_fresh` to achieve read-your-writes.

The `internal/datastore` is where to implement a new datastore. From my perspective, the opportunity lies beyond a simple SQLite datastore implementation: the D1 API offers compelling features to turn this into a first-class D1 datastore implementation:
- You could use the HTTP API, meaning you don't have to deal with the challenges associated with connection pools
- The Sessions API would allow you to use bookmarks and achieve read-your-write.

The challenges I see are:
- Based on the premise that it offers _sequential consistency_, it's unclear if it provides those guarantees for multi-statement transactions. Implementing some parts of the SpiceDB Datastore API without it will be tricky.
- Scaling SpiceDB to more than one replica in Cloudflare Containers: one is enough for many use cases, but if you want to leverage SpiceDB's clustering mechanism, service discovery will be needed in Cloudflare to have SpiceDB containers discover each other

**Comment by verdverm** [comment]
Adding a couple of links

- DOs have access to transactional and strongly consistent storage (https://developers.cloudflare.com/durable-objects/api/storage-api/)
- There is a vertical scaling limit (1000rps), i.e. one cannot simply run more copies of a container to scale. There would be no need or way to run SpiceDB in cluster mode. The intention is to scale with DO, which likely means that sharding is the means to distribute work (https://developers.cloudflare.com/durable-objects/platform/limits/#how-much-work-can-a-single-durable-object-do)
