### ISSUE TITLE
Deduplicate dispatching within a short window

### ISSUE THREAD

**Issue by jzelinskie** [authzed/spicedb#20]
When the same read-only requests occur within a configurable window of time, a single dispatch can be performed to fetch their results.

A useful library for implementing this is the [golang.org/x/sync/singleflight][singleflight].

[singleflight]: https://pkg.go.dev/golang.org/x/sync/singleflight

**Comment by jzelinskie** [comment]
Closed by #1607 #1617

**Comment by vroldanbet** [comment]
@jzelinskie do we want to keep this open until the rest of the API methods also see dispatch singleflighted?

**Comment by jzelinskie** [comment]
I don't think so because it's nontrivial to add it to streaming results
