### ISSUE TITLE
GOMAXPROCS, GOMEMLIMIT logs emitted on all CLI commands

### ISSUE THREAD

**Issue by jzelinskie** [authzed/spicedb#2010]
### What platforms are affected?

linux, macos, windows

### What architectures are affected?

amd64, arm64

### What SpiceDB version are you using?

v.1.31.1

### Steps to Reproduce

1. Install SpiceDB v1.31.1
2. Run any command

### Expected Result

log-level is respected

### Actual Result

```
$ spicedb version
{"level":"debug","message":"maxprocs: Leaving GOMAXPROCS=10: CPU quota undefined"}
{"level":"info","time":"2024-08-01T11:25:19-04:00","GOMEMLIMIT":61847529062,"package":"github.com/KimMachineGun/automemlimit/memlimit","message":"GOMEMLIMIT is updated"}
spicedb v1.35.1
{"level":"debug","message":"maxprocs: No GOMAXPROCS change to reset"}
```

**Comment by jzelinskie** [comment]
cc @tstirrat15

**Comment by tstirrat15** [comment]
It kinda looks like we're [explicitly stepping outside](https://github.com/authzed/spicedb/pull/1921/files#diff-78a58e360fdc2fe7e5a2eb972896f0fff0ad1e584ca8e60c77d428008bc60b88R38-R57) of the configured logging context. @vroldanbet was this intentional? Is it worth documenting?
