### ISSUE TITLE
Add linter to enforce usage of VT versions of marshallers/unmarshallers

### ISSUE THREAD

**Issue by tstirrat15** [authzed/spicedb#2036]
### Problem Statement

They're more performant and should be used anywhere we're doing this work. A linter will help us keep track of them.

### Solution Brainstorm

Write a linter

**Comment by tstirrat15** [comment]
Here's an example that the linter should catch: https://github.com/authzed/spicedb/blob/d77601bfe8b927c78d348144684bfa972b14e199/internal/datastore/memdb/readwrite.go#L268

**Comment by vroldanbet** [comment]
I recall that specifically there was some divergence in the serialization of VT and protobuf that led to some errors, this may not be the case anymore

**Comment by tstirrat15** [comment]
@vroldanbet I think that was probably this: https://github.com/planetscale/vtprotobuf/issues/61

We observed a problem as a result of it, and we fixed the problem by bumping to the most recent version of the lib.

**Comment by josephschorr** [comment]
Fixed by #2043
