### ISSUE TITLE
Embed SpiceDB as a library inside services written in Go

### ISSUE THREAD

**Issue by stanislavprokopov** [authzed/spicedb#205]
Is it possible to embed SpiceDB as a library inside a service written in Go to handle permissions?
If not then would you consider refactoring the code so that this use case would also be possible?

**Comment by arashpayan** [comment]
I'd like to add another example for the embedded use case. I completely understand that the raison d'être of Zanzibar is that it's distributed+scalable+reliable, but whether intended or not, Zanzibar (and SpiceDB in particular) is a really simple system for modelling permissions and querying them. And if there's even a modest amount of complexity in the permissions, which always creeps into the scope of projects, a Zanzibar based model can be easily augmented to support it. It's much simpler than writing a custom permissions system with all the necessary backend code to support it.

You're probably asking why the distributed and scalable attributes don't matter as much. It's because (as @stanislavprokopov pointed out) these are for applications that will never run on anything more than one server. They're just uninteresting (though critical) business applications that only serve a couple users at a time simultaneously with a max of 100 users registered on the server. I'm talking on the order of 2 queries a minute. Not exactly Google scale. :stuck_out_tongue: 

In the environments above, simplicity of deployment and maintenance surpasses any thoughts of scalability. A static Go binary with Spice DB embedded would be incredible.

Of course, I realize that you're trying to launch a profitable company, and this particular use case doesn't lend itself to monetization. The only comparable example I know of would be the way SQLite makes money. https://www.sqlite.org/prosupport.html

Anyway, please don't interpret this comment as a pushy/demand request for support on open source software. I'm just an enthusiastic user sharing a suggestion. Even if this never happens, I'll still be using it for any project of mine that requires anything more than 'admin/not admin' style permissions. :slightly_smiling_face:

**Comment by jzelinskie** [comment]
I don't think that restricting SpiceDB to only being a networked service is at odds with the Authzed business model -- the more people using the software Authzed builds, the more likely they'll be able to derive value from the paid products. 

That being said, I think the biggest reason that we've kept these libraries internal is that we're still breaking APIs regularly as we discover the right abstractions. As we have the need for code sharing in tools outside of SpiceDB, we've been slowly moving things out of internal and into the pkg directory.

One of recent example where we've opened things up is the CLI interface which can be found in `pkg/cmd`. I think that today you could embed SpiceDB in a binary by using this package to construct a gRPC server then using a gRPC client in the same process to communicate over a unix socket/shared memory/buffered memory. This might not be the deal UX, but it works today.

I'm willing to spend the rest of this issue discussing the actual desired UX for a library meant to embed SpiceDB. I don't think we need additional convincing that it'd be valuable.

**Comment by arashpayan** [comment]
I'm still very interested in this functionality.

Here's a very rough interface that I think I might be useful. Please read it with a skeptical eye, because I don't have much experience with the internals of SpiceDB and I'm positive that I'm overlooking functionality other folks would want from an embedded SpiceDB.

``` go
package spicedb

// The minimum required attributes to start an instance are in the configuration
type Config struct {
	DBURI string
	// one of cockroachdb, postgres, etc.
	DBEngine DBEngineType
	// so the embedding application can control stdout and stderr (maybe this should be in Options?)
	Logger Logger
}

// SpiceDB has tons of options in the CLI, and I'm sure some subset would make sense here, but I'm not confident enough to make any suggestions here.
type Options struct {
	
}

type Server interface {
	// just returns an instance of an *authzed.Client that we're already familiar with. Though if some other interface is easier to expose for the sake of this implementation, I'd be fine with that too.
	NewClient() *authzed.Client	// no token required
	Shutdown(context.Context) error
}

func Start(cfg Config, opts *Options) (Server, error) {
	// implementation
	// - connects to the database
	// - migrates to HEAD everytime
	// - other stuff?
}
```

**Comment by vroldanbet** [comment]
@arashpayan I think it should be possible to embed a SpiceDB server into another process. Have you tried that out and concluded it wasn't possible?

**Comment by arashpayan** [comment]
@vroldanbet No, I haven't even tried it. If any of the SpiceDB folks think that has a chance of success I can take a look at it in April, but my understanding from the above discussion was that there are still internal types that need to be exported. Granted, things may have changed since the WASM changes landed.

**Comment by vroldanbet** [comment]
@arashpayan I suspect that's the case: I've recently implemented an application that runs a SpiceDB with MemDB embedded - I think it should be possible. Feel free to report anything you might find here!

**Comment by arashpayan** [comment]
@vroldanbet Thanks. I'll give it a try in April and report back what I find. Do you have any suggestions/tips/code from your application that you can share here to aid in my work?

**Comment by vroldanbet** [comment]
Yeah, I think you could take a look at the testserver package, used to spin spicedb instances in integration tests. Most of the code used there is in `pkg`, and for the one that isn't, you should be able to find an exported alternative:

https://github.com/authzed/spicedb/blob/0c25ac283996945af91da101d4865920c371b67c/internal/testserver/server.go#L51-L116

**Comment by josephschorr** [comment]
@stanislavprokopov @arashpayan Any further guidance needed on this?

**Comment by stanislavprokopov** [comment]
Well based on the [example provided](https://github.com/authzed/spicedb/issues/205#issuecomment-1479496605) its clearly possible to customize parts of the spicedb server and use custom storage or customise the handlers and some other parts of the server, but based on the current codebase it doesnt look like its still possible to use spicedb as a library to handle permissions checks only, without all the other unrelated stuff, because the critical parts that actually perform these checks [are still located in the internal package](https://github.com/authzed/spicedb/blob/5b4dfd18d9cfa8856fb44e32606fe3bd50224351/internal/graph/computed/computecheck.go#L52), correct me if I am wrong.

What I would like to have is a way to do smth like this:
```
someDataStore := db.NewDatastore()
permissions := spicedb.NewPermissionsService(someDataStore)

if !permissions.Check(CheckParameters, resourceID) {
    // Return 401
}
```

spicedb is great if you were to build a large project, then surely spinning up one more service for permission handling is ok, but for smth smaller, thats a clear overkill and there is nothing out there that can provide the same fine-grained permissions check.

**Comment by ecordell** [comment]
Generally you'll want to use the objects in `pkg/cmd` to configure an in-process SpiceDB; these are the public interfaces to the internal code.

Here's an example of how to build an interface like you're asking for @stanislavprokopov (note that no internal packages are used):

```go
package main

import (
	"context"
	"fmt"
	"time"

	v1 "github.com/authzed/authzed-go/proto/authzed/api/v1"
	"google.golang.org/grpc"

	"github.com/authzed/spicedb/pkg/cmd/datastore"
	"github.com/authzed/spicedb/pkg/cmd/server"
	"github.com/authzed/spicedb/pkg/cmd/util"
)

type PermissionService struct {
	v1.PermissionsServiceClient
	Schema v1.SchemaServiceClient
	close  func()
}

func NewPermissionsService(ds datastore.Config) (*PermissionService, error) {
package main

import (
	"context"
	"fmt"
	"time"

	v1 "github.com/authzed/authzed-go/proto/authzed/api/v1"
	"google.golang.org/grpc"

	"github.com/authzed/spicedb/pkg/cmd/datastore"
	"github.com/authzed/spicedb/pkg/cmd/server"
	"github.com/authzed/spicedb/pkg/cmd/util"
)

type PermissionService struct {
	v1.PermissionsServiceClient
	Schema v1.SchemaServiceClient
	close  func()
}

func NewPermissionsService(ds datastore.Config) (*PermissionService, error) {
	ctx, cancel := context.WithCancel(context.Background())
	srv, err := server.NewConfigWithOptions(
		server.WithDatastoreConfig(ds),
		server.WithDispatchMaxDepth(50),
		server.WithMaximumPreconditionCount(10),
		server.WithMaximumUpdatesPerWrite(1000),
		server.WithStreamingAPITimeout(30*time.Second),
		server.WithMaxCaveatContextSize(4096),
		server.WithMaxRelationshipContextSize(1024),
		server.WithGRPCServer(util.GRPCServerConfig{
			Network: util.BufferedNetwork,
			Enabled: true,
		}),
		server.WithSchemaPrefixesRequired(false),
		server.WithGRPCAuthFunc(func(ctx context.Context) (context.Context, error) {
			return ctx, nil
		}),
		server.WithHTTPGateway(util.HTTPServerConfig{HTTPEnabled: false}),
		server.WithDashboardAPI(util.HTTPServerConfig{HTTPEnabled: false}),
		server.WithMetricsAPI(util.HTTPServerConfig{HTTPEnabled: false}),
		server.WithDispatchServer(util.GRPCServerConfig{Enabled: false}),
	).Complete(ctx)
	if err != nil {
		cancel()
		return nil, err
	}

	go func() {
		if err := srv.Run(ctx); err != nil {
			fmt.Println(err)
		}
	}()

	conn, err := srv.GRPCDialContext(ctx, grpc.WithBlock())
	if err != nil {
		cancel()
		return nil, err
	}

	return &PermissionService{
		PermissionsServiceClient: v1.NewPermissionsServiceClient(conn),
		Schema:                   v1.NewSchemaServiceClient(conn),
		close:                    cancel,
	}, nil
}

func (p *PermissionService) Close() {
	p.close()
}

func main() {
	emptyDS := datastore.NewConfigWithOptionsAndDefaults(
		datastore.WithEngine(datastore.MemoryEngine),
		datastore.WithGCWindow(10*time.Hour),
	)
	permissions, err := NewPermissionsService(*emptyDS)
	if err != nil {
		panic(err)
	}
	defer permissions.Close()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	_, err = permissions.Schema.WriteSchema(ctx, &v1.WriteSchemaRequest{
		Schema: `
			definition user {}

			definition resource {
				relation writer: user
				relation viewer: user

				permission write = writer
				permission view = viewer + writer
			}
		`,
	})
	if err != nil {
		panic(err)
	}

	_, err = permissions.WriteRelationships(ctx, &v1.WriteRelationshipsRequest{
		Updates: []*v1.RelationshipUpdate{{
			Operation: v1.RelationshipUpdate_OPERATION_TOUCH,
			Relationship: &v1.Relationship{
				Resource: &v1.ObjectReference{ObjectType: "resource", ObjectId: "foo"},
				Relation: "writer",
				Subject:  &v1.SubjectReference{Object: &v1.ObjectReference{ObjectType: "user", ObjectId: "me"}},
			},
		}},
	})
	if err != nil {
		panic(err)
	}

	canView, err := permissions.CheckPermission(ctx, &v1.CheckPermissionRequest{
		Resource:   &v1.ObjectReference{ObjectType: "resource", ObjectId: "foo"},
		Permission: "view",
		Subject:    &v1.SubjectReference{Object: &v1.ObjectReference{ObjectType: "user", ObjectId: "me"}},
	})
	if err != nil {
		panic(err)
	}
	fmt.Println(canView.Permissionship)
}
```

This example uses the memdb, but you can pass in your own config for an external datastore; everything you can configure via CLI flags can be configured with the packages above.

Note that if you embed spicedb like this with an external store, but don't configure dispatch / expose the dispatch api, you'll miss out on subproblem caching and the distributed computation check results. But if your problem fits in memory, embedding can make more sense.

**Comment by stanislavprokopov** [comment]
Thanks for the example, it looks similar to thing that is happening in testserver package, yes, it works but as far as I can tell you are still spinning up the whole spicedb server, including GRPC, metrics api, dashboard api, http gw, etc. And all permission checks are going throughout GRPC calls. I would prefer a simpler solution without all the stuff that's actually not necessary for a permission check.

**Comment by arashpayan** [comment]
Thanks @ecordell. What you shared looks good to me. I'd probably wrap that all up into a helper package in any project(s) I would need it in (to simplify initialization), but that looks like all the functionality I'd need.

**Comment by josephschorr** [comment]
> whole spicedb server, including GRPC, metrics api, dashboard api, http gw

Actually, most of these are disabled as per this config:

```
		server.WithHTTPGateway(util.HTTPServerConfig{HTTPEnabled: false}),
		server.WithDashboardAPI(util.HTTPServerConfig{HTTPEnabled: false}),
		server.WithMetricsAPI(util.HTTPServerConfig{HTTPEnabled: false}),
		server.WithDispatchServer(util.GRPCServerConfig{Enabled: false}),
```

As for gRPC itself, yes, you are calling via gRPC, but that can be done over a buffcon in-memory, so the overhead is minimal:

```
	server.WithGRPCServer(util.GRPCServerConfig{
			Network: util.BufferedNetwork,
			Enabled: true,
		}),
```

This is how we ourselves use SpiceDB as an embedded system

**Comment by vroldanbet** [comment]
I've added an example to github.com/authzed/examples in https://github.com/authzed/examples/pull/10

Closing this, if folks have additional feedback on how doing this could be improved, please open new issues with your requests 🙏
