### ISSUE TITLE
Installing spicedb in windows using choco

### ISSUE THREAD

**Issue by hmasum52** [authzed/spicedb#2053]
### What platforms are affected?

windows

### What architectures are affected?

amd64

### What SpiceDB version are you using?

latest

### Steps to Reproduce

```choco install spicedb```

### Expected Result

spicedb installed

### Actual Result

![image](https://github.com/user-attachments/assets/11462bc9-88cb-4267-b26a-8cca9647156c)

**Comment by tstirrat15** [comment]
This will be fixed by #1879 - we've got a couple of bugs in the build process to iron out.

**Comment by tstirrat15** [comment]
That PR is merged, but we won't see whether it worked until the next SpiceDB release. v1.36.0 should be forthcoming shortly and then you can give it another go.

**Comment by joeriddles** [comment]
@tstirrat15 looks like there is still no Windows release in v1.36.x nor v1.37.0.
