### ISSUE TITLE
Publish to deb and rpm releases to fury.io

### ISSUE THREAD

**Issue by jzelinskie** [authzed/spicedb#233]
Because this project uses [goreleaser pro], we can easily [publish to fury.io][fury-pub] on release so that Deb and RPM based Linux distros can have a source to configure, rather than manually downloading these packages from the releases page.

[goreleaser pro]: https://goreleaser.com/pro/
[fury-pub]: https://goreleaser.com/customization/fury/

**Comment by josephschorr** [comment]
Already done: https://github.com/authzed/spicedb#installing-the-binary
