### ISSUE TITLE
CLI configuration errors should return instead of fatal logging

### ISSUE THREAD

**Issue by jzelinskie** [authzed/spicedb#265]
When CLI flags are misconfigured or invalid, the error should be returned to the cobra command RunFuncE rather than using `log.Fatal()`. This provides a consistent error experience for user-driven errors rather than ones caused by machine failures.

**Comment by bryanhuhta** [comment]
Returning an error to `RunE` is a step in the right direction, but will still result in output that's a little wonky. To illustrate, here is the `spicedb migrate` command as it is now:

```
$ spicedb migrate 1 --datastore-engine bad
9:08PM INF set log level new level=info
9:08PM INF set tracing provider new provider=none
9:08PM FTL cannot migrate datastore engine type engine=bad
exit status 1
```

And here is it when using `RunE` and returning user errors:

```
$ spicedb migrate 1 --datastore-engine bad 
9:10PM INF set log level new level=info
9:10PM INF set tracing provider new provider=none
Error: cannot migrate datastore engine type: bad
Usage:
  spicedb migrate [revision] [flags]

Flags:
      --datastore-conn-uri string   connection string used by remote datastores (e.g. "postgres://postgres:password@localhost:5432/spicedb")
      --datastore-engine string     type of datastore to initialize ("memory", "postgres", "cockroachdb") (default "memory")
  -h, --help                        help for migrate

Global Flags:
      --log-format string                 format of logs ("auto", "human", "json") (default "auto")
      --log-level string                  verbosity of logging ("trace", "debug", "info", "warn", "error") (default "info")
      --otel-jaeger-endpoint string       jaeger collector endpoint (default "http://jaeger:14268/api/traces")
      --otel-jaeger-service-name string   jaeger service name for trace data (default "spicedb")
      --otel-provider string              opentelemetry provider for tracing ("none", "jaeger") (default "none")
```

The logs com from `cobrautil.ZeroLogPreRunE` and `cobrautil.OpenTelemetryPreRunE`  doing some logging when they start up.

https://github.com/authzed/spicedb/blob/95cd1dce6f74e6d43641e9a57cd0a8932907d0e1/pkg/cmd/defaults.go#L30-L38

The question is: Is no logging on a user error a hard requirement or is it OK if there are some logs before the user error is reported?

**Comment by jzelinskie** [comment]
I think the goal shouldn't be to prevent all logging before providing the error, but instead establish a recognizable pattern that the user misconfigured something rather than an internal failure occurring.
