### ISSUE TITLE
Relationships with expiry / TTL

### ISSUE THREAD

**Issue by vroldanbet** [authzed/spicedb#282]
Hey authzed team! 👋🏻  Opening up this issue to gauge interest on relationships with expiration 

## The ask

`Write` API should make it possible to write relationships with an expiration. Past the expiration, any operation that makes use of the relationship (`Read`, `Check`, `Lookup`, `Expand`... ) would effectively treat it as non-existent.

**Comment by josephschorr** [comment]
Native support is now being tested: https://github.com/authzed/spicedb/pull/2152
