### ISSUE TITLE
Support Multiple Preshared Keys

### ISSUE THREAD

**Issue by ecordell** [authzed/spicedb#288]
The `--grpc-preshared-key` flag currently takes a single string as a value.

This should instead support multiple values (i.e. with a cobra `StringSlice`) so that users can rotate keys easily.

**Comment by relcodedev** [comment]
I see it is used with multiple --grpc-preshared-key at command line.  Is there a way to use environment variables also?

**Comment by josephschorr** [comment]
You can specify the different keys using a comma between them

**Comment by relcodedev** [comment]
[like]  Edgar Robles reacted to your message:
________________________________
