### ISSUE TITLE
Remove/Delete an object and all its relations (including used as subjects) in one call

### ISSUE THREAD

**Issue by alvarezh** [authzed/spicedb#315]
Given this schema:
```
definition user {}

definition user_group {
	relation member: user
}

definition organization {
	relation member: user_group#member
}
```

And these relationships:
```
user_group:organization_members#member@user:user1
user_group:organization_members#member@user:user2
organization:myOrganization#member@organization_members#member
```

I have to run two calls to remove the existence of "organization_members" in its entirety:

```
_, err := a.client.DeleteRelationships(ctx, &v1.DeleteRelationshipsRequest{
    RelationshipFilter: &v1.RelationshipFilter{
        ResourceType:           "user_group",
        OptionalResourceId:  "organization_members",
    },
})

// This call removes these relationships
// user_group:organization_members#member@user:user1
// user_group:organization_members#member@user:user2

_, err = a.client.DeleteRelationships(ctx, &v1.DeleteRelationshipsRequest{
    RelationshipFilter: &v1.RelationshipFilter{
        ResourceType: "organization",
        OptionalSubjectFilter: &v1.SubjectFilter{
            SubjectType:       "user_group",
            OptionalSubjectId: "organization_members",
            OptionalRelation: &v1.SubjectFilter_RelationFilter{
                Relation: "member",
            },
        },
    },
})

// This call removes this relationship
// organization:myOrganization#member@organization_members#member
```

I'd like to have a call to remove the object and all its relations, that way I can be sure that there isn't any traces of it in the DB.

**Comment by PJEstrada** [comment]
Would also find this super useful for handling delete operations on our app, usually we leverage a cascade delete on our relational database, so a similar idea would make it easier to syncronize the state on spicedb.

**Comment by tadejsv** [comment]
Would also really like to see this feature. I have a hierarchy of objects 3 layers deep, so every time an object from the "top" class gets deleted, I first need to run an SQL call on the database to figure out what related resources need to be deleted. 

Would be really convenient if SpiceDB could do this automatically.
