### ISSUE TITLE
Push releases to various container registries

### ISSUE THREAD

**Issue by jzelinskie** [authzed/spicedb#32]
There are various registries with different retention policies for container images.
It is probably worth setting up redundant repositories to hedge against losing any images.

Potential registries:
- ~~Quay~~ (already being used)
- Docker Hub
- GitHub

**Comment by josegonzalez** [comment]
Would be cool to have this pushed automatically to Docker Hub, as that is where most folks go to by default to find docker images.

**Comment by jauderho** [comment]
Here's a first pass at having containers deployed to Docker Hub and GHCR. 

- https://hub.docker.com/repository/docker/jauderho/spicedb/tags?page=1&ordering=last_updated
- https://github.com/jauderho/dockerfiles/pkgs/container/spicedb

Dockerfile repo is here: https://github.com/jauderho/dockerfiles/tree/main/spicedb

On the plus side, ppc64le and s390x versions are built (not tested). linux/386, linux/arm/v6 and linux/arm/v7 had build errors but I have not had a chance to figure out why yet.

**Comment by jzelinskie** [comment]
Fixed in #479
