### ISSUE TITLE
Consistent CLI flags with zed

### ISSUE THREAD

**Issue by jzelinskie** [authzed/spicedb#4]
There are a variety of command-line flags that are shared across Authzed projects that do the same thing, but are named differently.

This issue should track documenting those shared flags and updating them so that everything is consistent.
Where it makes sense, flags can be upstreamed into [cobrautil], like the zerolog flags already are.

[cobrautil]: https://github.com/jzelinskie/cobrautil

**Comment by josephschorr** [comment]
Most of these flags have been moved into cobrautil
