### ISSUE TITLE
Embedded message failed validation

### ISSUE THREAD

**Issue by tagantroy** [authzed/spicedb#407]
I'm using email address as subjects id, it works perfectly for most of queries, but fails for readRelationships and lookupResources. 
For example:
```
    override suspend fun getAllAvailableProjects(userEmail: String): List<String> {
        val req = PermissionService.ReadRelationshipsRequest.newBuilder()
            .setConsistency(
                PermissionService.Consistency.newBuilder()
                    .setFullyConsistent(true)
            )
            .setRelationshipFilter(
                PermissionService.RelationshipFilter.newBuilder()
                    .setResourceType("$namespace/project")
                    .setOptionalRelation(viewerRelation)
                    .setOptionalSubjectFilter(
                        PermissionService.SubjectFilter.newBuilder()
                            .setSubjectType("$namespace/user")
                            .setOptionalSubjectId(userEmail)
                    )
            )
            .build()
        val res = permissionsService.readRelationships(req)
        ...
    }
```
Fails for email request with next errror:
```
INVALID_ARGUMENT: invalid ReadRelationshipsRequest.RelationshipFilter: embedded message failed validation | caused by: invalid RelationshipFilter.OptionalSubjectFilter: embedded message failed validation | caused by: invalid SubjectFilter.OptionalSubjectId: value does not match regex pattern "^(([a-zA-Z0-9_][a-zA-Z0-9/_-]{0,127})|\\*)?$"
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid ReadRelationshipsRequest.RelationshipFilter: embedded message failed validation | caused by: invalid RelationshipFilter.OptionalSubjectFilter: embedded message failed validation | caused by: invalid SubjectFilter.OptionalSubjectId: value does not match regex pattern "^(([a-zA-Z0-9_][a-zA-Z0-9/_-]{0,127})|\\*)?$"
```

in the same time writeRelationships and checkPermission works with email as subject id. Is it inconsistency in API or I'm missing something? Is it okay to use email or not? 
What is recommended format/type for user identifiers?

**Comment by josephschorr** [comment]
Hi @tagantroy,

Objects IDs with `@` signs should be disallowed currently; if they aren't, that's a bug in one of the validation paths (I'll check into that now). We may re-evaluate that restriction in the future.

We generally recommend against using e-mail addresses as object IDs, as they are not known to be universally stable. Instead, we recommend using either a unique ID from your authn engine (such as a `sub` field if given via OAuth), or a primary key for a user table (if you have one). If you do want to use email addresses as object IDs and can guarantee their long-term stability, then we recommend base64 encoding them to place them into object IDs.

**Comment by tagantroy** [comment]
Hi @josephschorr, Thanks for quick reply! 
I think using sub provided by Auth0 should work in my case.
It would be nice to include this info to guidelines/docs on the website :) 

Thanks for this awesome project!

**Comment by josephschorr** [comment]
@tagantroy Will definitely file a documentation update for it! Sorry for the trouble!
