### ISSUE TITLE
Delay reporting healthy until dispatch is available

### ISSUE THREAD

**Issue by ecordell** [authzed/spicedb#421]
If dispatch is incorrectly configured or if the peer resolver is unavailable (as of right now [kuberesolver](https://github.com/sercand/kuberesolver) is the only option, there may be others in the future), SpiceDB will start up successfully and report that it's healthy, but all requests will hang while dispatch attempts to resolve a peer.

SpiceDB should delay setting the grpc service healthy until after an initial set of peers has been fetched. This gives a more immediate signal if the cluster is initially misconfigured (it never reports healthy) and will also help if a node starts while the peer service is temporarily unavailable (i.e. a pod starts but the kube api is unavailable).

This should only be done during initialization; after a node has started and begun communicating with peers it should remain in service even if there are network disruptions with other nodes or the peer resolver. The resolver being unavailable should not flip a healthy node to unhealthy.

**Comment by ecordell** [comment]
cc @vroldanbet

**Comment by josephschorr** [comment]
Fixed by #615
