### ISSUE TITLE
SpiceDB Clarification Please

### ISSUE THREAD

**Issue by lonnietc** [authzed/spicedb#465]
Hello,

Do I understand correctly in that Spice DB is a graph DB that uses a plugin backend and that is highly scalable?

Regarding the backends, are there any built-in besides in-memory?

I am interested in ultra-high scalable (think P2P applications) using a graph database and would like to find out what are the capabilities of SpiceDB in this regard.

**Comment by jakedt** [comment]
Hi,

It's more like a specialization of a graph DB for efficiently computing permissions. It's highly scalable _for that task_. There are a number of backend implementations: in-memory, CockroachDB, Cloud Spanner, and PostgreSQL.

I wouldn't recommend using SpiceDB as a generic graph database, but for the permissions portion of a P2P application, SpiceDB would likely be a great fit.
