### ISSUE TITLE
Unable to write tuples: extended protocol limited to 65535 parameters

### ISSUE THREAD

**Issue by gergof** [authzed/spicedb#476]
I was testing spiceDB for the last couple of days using the in-memory database. Now I would like to use postgres, but I get this error when I try to insert more than ~8000 relations at once.
I know that this is a limitation of postgres, but it would be nice if this would be handled by SpiceDB.

**Comment by josephschorr** [comment]
SpiceDB now handles this via a configurable limit on the API side: https://github.com/authzed/spicedb/pull/775
