### ISSUE TITLE
fail to start spice serve command if Datastore isn't ready

### ISSUE THREAD

**Issue by vroldanbet** [authzed/spicedb#482]
# Ask

`spicedb serve` should terminate with code non-zero if `Datastore.IsReady()` is false on bootstrap

# Context

During the development of a `Datastore` implementation based on MySQL we identified missing seeding that would prevent the `Datastore.IsReady()` from returning `true`, signaling that the `Datastore` is ready to serve operations.

Our surprise was that the deployment of SpiceDB, which runs `spicedb serve` succeeded, leaving the cluster "Healthy" from a kubernetes perspective, but otherwise completely unable to serve API calls because `Datastore.IsReady()` would prevent it. In a production scenario this would have caused an incident. From the perspective of the rollout of a new Kube `Deployment`, we would have expected it to never become healthy.

The proposal is to make sure `spicedb serve` terminate during the bootstrap sequence if `Datastore.IsReady()` is false.

**Comment by jzelinskie** [comment]
I think there could be a bit more discussion about how to fix this.

Another possibility is fleshing out the gRPC health endpoint to make this call so that Pods configured with proper healthiness/readiness probes won't route traffic to these instances until it's all green.

Maybe we could add a boolean `--datastore-exit-if-unready` so that simple deployments don't need scripts around calling a readiness API.

**Comment by vroldanbet** [comment]
@jzelinskie from a conceptual perspective of an `IsReady()` function, I'm OK with that 👍🏻  although I'd be wary of recommending using that for liveness probes (see https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html). Fortunately something folks are not forced to adopt it they don't need to.

The challenge I see is that the way `Datastore.IsReady()` is currently implemented in practice makes it unlikely a deployment will become healthy within a reasonable amount of time: they check whether the database is running at the HEAD migration. From my perspective that's akin to an **incorrect system configuration** (e.g. if you pass an incorrect flag value to `spicedb serve`, you return with exit code non-zero, right?), hence my suggestion to terminate the process. I'm not sure I can see a spicedb not having a migration run being in the realm of "a transient state the system will eventually recover from" 😕. 

Perhaps the problem here is that `IsReady()` is not a good fit to check for HEAD migrations?
