### ISSUE TITLE
Limitation of maximum length of 64 bytes on Object ID

### ISSUE THREAD

**Issue by krtkvrm** [authzed/spicedb#490]
We have Object IDs that are of a size larger than 64 bytes, and we get this error while adding it to spicedb:
```
 error: rpc error: code = InvalidArgument desc = invalid WriteRelationshipsRequest.Updates[0]: embedded message failed validation | caused by: invalid RelationshipUpdate.Relationship: embedded message failed validation | caused by: invalid Relationship.Resource: embedded message failed validation | caused by: invalid ObjectReference.ObjectId: value length must be at most 64 bytes on firehose
```
We wanted to know if there is any way to go around this? we were thinking of hashing the id to maybe md5sum or sha512 but this can give issues while debugging

thanks!

**Comment by josephschorr** [comment]
This is now 128 characters: https://github.com/authzed/api/blob/main/authzed/api/v1/core.proto#L45

**Comment by phdowling** [comment]
Hi @josephschorr - is there any deeper reason that the IDs could not be longer? 
We need to manage access to file paths, which can pretty easily exceed this length. We can create some sort of lookup table to translate the IDs in-flight, but this adds overhead we'd like to avoid. Would anything go substantially wrong if we change those 2 lines above to, say, 1024 bytes and recompile SpiceDB?

Alternatively, to phrase it as a feature request: would making the object ID length a configurable parameter be possible?
