### ISSUE TITLE
Audit the usage of Dispatcher and Datastore for use after being closed

### ISSUE THREAD

**Issue by jakedt** [authzed/spicedb#604]
Some of our fire-and-forgotten requests, that are no longer needed due to an earlier answer, can continue to use the datastore after it has been closed. We should probably track and audit each and every goroutine that we fire off for correctness and to prevent things from being used after they're closed.

**Comment by jzelinskie** [comment]
[Related to a Slack conversation](https://authzed.unthread.io/dashboard/inbox/all/conversations/af2ef8b1-d830-48d5-a6fc-2e6ced4484d9)
