### ISSUE TITLE
A confusing place in module lexer 

### ISSUE THREAD

**Issue by fearlessfe** [authzed/spicedb#619]
in the module lexer, the `lastNonWhitespaceToken` in struct `Lexer` means "The last token returned that is non-whitespace"

the only space that used `lastNonWhitespaceToken` in code is below
assign a TokenTypeWhitespace to lastNonWhitespaceToken
```
if t == TokenTypeWhitespace {
	l.lastNonWhitespaceToken = currentToken
}
```
should be like this?
```
if t != TokenTypeWhitespace {
	l.lastNonWhitespaceToken = currentToken
}
```

**Comment by ecordell** [comment]
Yeah that looks like a mistake to me too - luckily I don't see that value being used anywhere, so I don't think this has any impact.

@josephschorr did you have a plan for tracking this value? Can we remove it or should we change the implementation?

**Comment by fearlessfe** [comment]
yes, I'd like to take a PR. Just remove it?

**Comment by josephschorr** [comment]
Yep, just remove it
