### ISSUE TITLE
Support IAM database authentication for Postgres datastore

### ISSUE THREAD

**Issue by jhalleeupgrade** [authzed/spicedb#659]
As of now, there is only support for username:password in the connection string for Postgres. For those who use an AWS's hosted Postgres, it's preferable to use IAM database authentication.

**Comment by josephschorr** [comment]
@jhalleeupgrade any pointers on documentation on how that is enabled?

**Comment by jzelinskie** [comment]
I'm not sure what the best CLI UX looks like for this feature.

Because it looks like the password field is overloaded to provide this functionality, there is an interesting workaround that could be done now: write a tiny program that prints the output of `rdsutils.BuildAuthToken()` and then just use that value for the password on the SpiceDB serve command: `spicedb serve --datastore-engine postgres --datastore-uri "host=blahblah password=$(myProgram) ..."`.

**Comment by palacerteupgrade** [comment]
@jzelinskie I think we would need to provide a way to refresh at runtime, because the AWS Auth token has an expiration deadline.

**Comment by jzelinskie** [comment]
You're totally right that the value actually is short-lived. There's a lot of good discussion on [this issue for our Postgres library](https://github.com/jackc/pgx/issues/676). It looks like we should decide the UX for this and then we can add a `BeforeConnect` hook for connections to inject the "password" into the config.

**Comment by JeremyFossTemple** [comment]
It looks like the [postgres library](https://github.com/jackc/pgx/) supports an [environment variable](https://github.com/jackc/pgx/blob/6f90866f58807873816ae69f1e37d4a0fbcc8ddd/pgconn/config.go#L175) that specifies a [password file](https://www.postgresql.org/docs/current/libpq-pgpass.html) whose value is [read at connection time](https://github.com/jackc/pgx/blob/6f90866f58807873816ae69f1e37d4a0fbcc8ddd/pgconn/config.go#L362).  If that's right then one way of using IAM database authentication today for a SpiceDB Postgres datastore is to run a script that re-writes the file at an interval appropriate for keeping credentials valid.   Maybe some people might prefer the  [service file](https://www.cybertec-postgresql.com/en/pg_service-conf-the-forgotten-config-file/) over the password file.

**Comment by elebiodaslingshot** [comment]
Any updates on this?
