### ISSUE TITLE
Add support for Application Default Credentials for Cloud Spanner datastore

### ISSUE THREAD

**Issue by kirbyquerby** [authzed/spicedb#665]
The Cloud Spanner driver currently [requires a service account JSON file](https://docs.authzed.com/spicedb/selecting-a-datastore#cloud-spanner-beta).

Another way to authenticate with Google services is using [Application Default Credentials](https://cloud.google.com/docs/authentication/production#automatically), which allows one to authenticate with cloud APIs without manually supplying a service account file (one use case is when running on a GCE instance with a linked service account).

The Go client libraries support Application Default Credentials out of the box -- they're used by default if no credentials are supplied: https://pkg.go.dev/cloud.google.com/go?utm_source=godoc#hdr-Authentication_and_Authorization

For instance, for this line:
https://github.com/authzed/spicedb/blob/42f730ab06c8b9ec90b74f2d390454083a925627/internal/datastore/spanner/spanner.go#L74

The equivalent code using Application Default Credentials would be:
```go
 client, err := spanner.NewClient(context.Background(), database) 
```

Is it possible to add support for using Application Default Credentials to connect to Cloud Spanner? I'm willing to write the PR.

**Comment by jzelinskie** [comment]
I think we should make the best path the one of least resistance.

I think it'd be fine to relax the requirement for --datastore-spanner-credentials and make the default check for a service account and only check for credentials if one is missing.

**Comment by kirbyquerby** [comment]
Only after putting together a change did I think to test how SpiceDB currently behaves when `--datastore-spanner-credentials` is empty :facepalm: . It turns out passing `""` to `option.WithCredentialsFile()` is equivalent to not calling it at all, as it will leave `CredentialsFile` with its default value in the `DialSettings`: https://github.com/googleapis/google-api-go-client/blob/8937b912dbd8c13994279611ce091e74f2c4e05b/internal/settings.go#L30

Since SpiceDB doesn't check to make sure `--datastore-spanner-credentials` is provided, it will forward any empty/missing credentials path to the spanner client, which will then proceed to use application default credentials.

It's probably still worth updating the [documentation](https://github.com/authzed/docs/blob/8ae70d3af6f0fa7a7fbf8783333b5e7dda233837/docs/spicedb/selecting-a-datastore.md?plain=1#L123) and the flag descriptions ([migrate](https://github.com/authzed/spicedb/blob/42f730ab06c8b9ec90b74f2d390454083a925627/pkg/cmd/migrate.go#L25), [serve](https://github.com/authzed/spicedb/blob/42f730ab06c8b9ec90b74f2d390454083a925627/pkg/cmd/datastore/datastore.go#L116)) to describe this behavior.

**Comment by jzelinskie** [comment]
Oh nice! Would you like to open the PR updating the documentation? The best feature is one that you realize you already had and just needed to document, haha.

**Comment by kirbyquerby** [comment]
Sure :)
