### ISSUE TITLE
Tangential feedback on the Playground / on-boarding experience

### ISSUE THREAD

**Issue by LDMFD** [authzed/spicedb#675]
Hi, not sure this belongs here - would just like to pass feedback that the Playground appears to be unusable if it doesn't support having more than one instance open at a time.

For someone learning the platform, the ability to open samples alongside my own app is essential.

All that said, thanks for the great product! I am not deterred by this UX hiccup, in fact it is a subtle way to get people using the big brother `zed validate` 🙃

**Comment by alecmerdler** [comment]
The [SpiceDB Playground is now open-source](https://github.com/authzed/playground) and can be ran locally for as many instances as you want. I believe this addresses this issue can we can close it.
