### ISSUE TITLE
Graph view for the paths for a specific resource and subject.

### ISSUE THREAD

**Issue by shibupiriyath** [authzed/spicedb#693]
It would nice to have a graph view to test and see a resource to subject evaluation path.

Ref:
https://discord.com/channels/844600078504951838/844600078948630559/996082018569965578

**Comment by josephschorr** [comment]
Playground now has tracing under check watches:

<img width="1044" alt="Screen Shot 2023-01-19 at 4 36 10 PM" src="https://user-images.githubusercontent.com/4073002/213567384-a23244ad-9115-4c41-9db9-6c3398599209.png">

@shibupiriyath is this sufficient, or would you want a graphical view?

**Comment by josephschorr** [comment]
@shibupiriyath Checking in once more. If the tracing view is sufficient, please let me know

**Comment by josephschorr** [comment]
Closing; feel free to reopen if you need additional information or visualizations
