### ISSUE TITLE
PostrgreSQL datastores do not timeout on initialization

### ISSUE THREAD

**Issue by vroldanbet** [authzed/spicedb#741]
If PostgreSQL datastores are initialized on an unreachable/unresponsive database backend, the initialization hangs indefinitely, and the spicedb process wont report becoming healthy.

We can see this is caused by a missing deadline:

https://github.com/authzed/spicedb/blob/26d13e56948492537e02501c8d018e0def5ad204/internal/datastore/crdb/crdb.go#L92-L95

**Comment by vroldanbet** [comment]
This should be addressed for CRDB as of https://github.com/authzed/spicedb/pull/1042

**Comment by josephschorr** [comment]
@vroldanbet is this complete as of https://github.com/authzed/spicedb/blob/main/internal/datastore/postgres/postgres.go#L160?

**Comment by vroldanbet** [comment]
@josephschorr yup!
