### ISSUE TITLE
add backoff and jitter to CRDB retry logic

### ISSUE THREAD

**Issue by vroldanbet** [authzed/spicedb#748]
The retry logic in CRDB datastore does not have any backoff in place. In order to prevent worsening a scenario where the backend database is having a hard time keeping up, we should add a backoff with jitter to that logic.

https://github.com/authzed/spicedb/blob/4b38ab91ed80e10d7e96c921dbcafd78f39dda27/internal/datastore/crdb/tx.go#L54-L73

**Comment by JammUtkarsh** [comment]
Hey @vroldanbet,
I'm interested in contributing to the Issue and I'd like to learn more about it. I appreciate any information you can provide and look forward to contributing to the project.
Thank you,
Utkarsh Chourasia

**Comment by vroldanbet** [comment]
@JammUtkarsh 👋🏻 thanks for volunteering! There have been some recent discussions about how we handle CockroachDB retries and I'm not entirely sure it's worth pursuing this issue as it may be subject to change soon. I'd suggest looking for [another good first issue](https://github.com/authzed/spicedb/labels/hint%2Fgood%20first%20issue).

**Comment by ecordell** [comment]
This was done in #1294
