### ISSUE TITLE
ZedToken increasing latency instead of reducing it

### ISSUE THREAD

**Issue by sjaakiejj** [authzed/spicedb#800]
We've been using SpiceDB in production for a few months now at https://www.veed.io/ and have gradually been migrating our authorization data to it. We've attached a Postgres datasource, which now has a size of about 7GB and we've run into a bit of an unexpected problem.

The easiest way to explain it is by showing some metrics. 
<img width="914" alt="Screen_Shot_2022-09-06_at_13 38 34" src="https://user-images.githubusercontent.com/1705506/188695400-71e2b290-3844-4881-9369-4875b7067668.png">

As our data size grew from about 2-3 million data points to >10 million, we started noticing significant slowdowns on some user accounts, but not on others. Following the documentation, we had implemented ZedToken caching and use `atLeastAsFresh` consistency for a number of our users - which we found to be the exact users having issues with significant slowdowns. Our investigation into the issue resulted in the discovery that making use of ZedTokens actually slowed down requests by a factor of 100. We've now set everything to be fully consistent - and the results speak for themselves:
<img width="465" alt="Screen_Shot_2022-09-06_at_13 39 36" src="https://user-images.githubusercontent.com/1705506/188696036-fe835978-5ede-4282-aa06-af71ec1875e4.png">

Slowdowns have completely stopped and latency dropped down to 300ms, but this isn't the behaviour I'd expect. Considering we expect our data set to grow significantly over the coming months, I do believe we are going to need to rely on ZedTokens to ensure our latency doesn't grow again - especially since the solution wouldn't be as straightforward as it was now when fully consistent calls become problematic.

**Comment by josephschorr** [comment]
@sjaakiejj Were the zedtokens stored *per user* or on the resource(s) being checked? Can you give some insight into the kinds of checks that were slowing down?

**Comment by sjaakiejj** [comment]
Hi @josephschorr,

I think easiest if I share a simplified version of our schema:
```
definition veed/user {}

definition veed/workspace {
  relation editor: veed/user
  relation reader: veed/user

  permission read = editor + reader
  permission write = editor
}
```

Every time we link a user to a workspace, e.g. using this:
```typescript
const addWorkspaceMember = async (workspaceId: string, user: v1.ObjectReference) => {
    const resource = getObjectReference(workspaceId);

    const writeRequest = v1.WriteRelationshipsRequest.create({
      updates: [
        v1.RelationshipUpdate.create({
          relationship: v1.Relationship.create({
            resource,
            relation: "editor",
            subject: v1.SubjectReference.create({
              object: user,
            }),
          }),
          operation: v1.RelationshipUpdate_Operation.CREATE,
        }),
      ],
    });

    const write = promisify(this.client.writeRelationships).bind(this.client);
    return write(writeRequest);
 }
```

A ZedToken is returned. We then store that ZedToken alongside our workspace in our database. Then, whenever we need to check if a given user has permissions to access the workspace, we perform a check like this:
```typescript
const checkPermissions = (
    user: v1.ObjectReference, // = userToCheck
    resourceId: string, // = "workspaceId"
    relation: string, // = "read"
    consistency: Consistency // = atLeastAsFresh, 
    atLeastAsFresh?: ZedToken // = zedTokenFromWorkspaceTable
  ) => {
    const resource = this.getObjectReference(resourceId);

    const checkRequest = v1.CheckPermissionRequest.create({
      resource,
      permission: relation,
      subject: v1.SubjectReference.create({
        object: user,
      }),
      consistency: this.getConsistency(consistency, atLeastAsFresh),
    });

    const check = promisify(this.client.checkPermission).bind(this.client);
    const res = await check(checkRequest);
    return (
      res?.permissionship ===
      CheckPermissionResponse_Permissionship.HAS_PERMISSION
    );
  }
```

This then takes about 5-10 seconds to return. The same behaviour applies when we set consistency to `minimizeLatency`. However, once we set consistency to `fullyConsistent`, it returns within 50ms

**Comment by josephschorr** [comment]
@sjaakiejj Do you have GC turned on in your Postgres datastore and, if so, how many transactions are in your transactions table?

**Comment by sjaakiejj** [comment]
We're starting SpiceDB with the following command:
```
docker run serve --grpc-preshared-key <API_KEY> --datastore-engine postgres --datastore-conn-uri <DB_URL>
```
We're currently at 13,915,976 transactions and 13,846,738 relationship tuples

**Comment by josephschorr** [comment]
@sjaakiejj Are all of those transactions within your configured GC window? That seems like a lot of transactions, unless you're writing that many relationships often

**Comment by sjaakiejj** [comment]
What's the default GC window? Or is GC turned off by default?

**Comment by josephschorr** [comment]
@sjaakiejj GC should be turned on by default, and the default window is 24 hours. That means, if GC is working, that your transactions table should only have those from within a 24 hour period.

**Comment by josephschorr** [comment]
@sjaakiejj Just checking in on this one; before we continue our investigation, can you confirm that GC is active and that those ~13M transactions are within the 24 hour period?

**Comment by sjaakiejj** [comment]
Hey Joseph,

After some further investigation based on your suggestion that 13m transactions were too high, we found out that the migrations hadn't been applied properly. So whilst GC was turned on and triggered regularly, it appears as though it wasn't able to actually remove any transactions because of this, causing the slowdowns we were seeing.

It did surprise me though that there wasn't a clearer indication that the migrations had failed to apply - the service boots as usual and there was nothing in the logs to indicate that this is what had happened.

**Comment by josephschorr** [comment]
@sjaakiejj The health check in v1.12 or later should fail to return healthy if the database had not fully migrated to the correct revision.

**Comment by josephschorr** [comment]
Closing as the health check should now report whether the system is at the correct revision
