### ISSUE TITLE
Set debug.SetMemoryLimit based on Kubernetes environment

### ISSUE THREAD

**Issue by jakedt** [authzed/spicedb#819]
SpiceDB often runs in memory constrained environments. We should set the soft memory limit based on how much memory the container that we're running in has.

https://pkg.go.dev/runtime/debug@master#SetMemoryLimit

**Comment by jzelinskie** [comment]
Searched GitHub to see how folks were using this, to try and see if there was a library that looked into cgroups and called this function. I did not find anything that accomplished that, but I did discover how TiDB is tuning the runtime with that call: https://pkg.go.dev/github.com/pingcap/tidb/util/gctuner?utm_source=godoc

**Comment by vroldanbet** [comment]
We can close this now that we are using GOMEMLIMIT
